origin
GIT 367d3fd50566a313946fa9c5b2116a81bf3807e4

commit bc9dc9d5eec908806f1b15c9ec2253d44dcf7835
Author: Bjørn Mork <bjorn@mork.no>
Date:   Mon May 30 17:40:42 2016 +0300

    lib/uuid.c: use correct offset in uuid parser
    
    Use '+ 0' and '+ 1' as offsets, like they were intended, instead of
    adding to the result.
    
    Fixes: 2b1b0d66704a ("lib/uuid.c: introduce a few more generic helpers")
    Signed-off-by: Bjørn Mork <bjorn@mork.no>
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit cfaff0e515b544fa0a9cdc58a975cc629ff3bc17
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Mon May 30 17:40:41 2016 +0300

    lib/uuid: add a test module
    
    It appears that somehow I missed a test of the latest UUID rework which
    landed in the kernel.  Present a small test module to avoid such cases
    in the future.
    
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit 545ebd9a9be6bcbcf3e8dc24b874bfd634131946
Author: Linus Walleij <linus.walleij@linaro.org>
Date:   Mon May 30 17:11:59 2016 +0200

    gpio: drop lock before reading GPIO direction
    
    When adding the gpiochip, the GPIO HW drivers' callback get_direction()
    could get called in atomic context. Some of the GPIO HW drivers may
    sleep when accessing the register.
    
    Move the lock before initializing the descriptors.
    
    Reported-by: Laxman Dewangan <ldewangan@nvidia.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 54d77198fdfbc4f0fe11b4252c1d9c97d51a3264
Author: Linus Walleij <linus.walleij@linaro.org>
Date:   Mon May 30 16:48:39 2016 +0200

    gpio: bail out silently on NULL descriptors
    
    In fdeb8e1547cb9dd39d5d7223b33f3565cf86c28e
    ("gpio: reflect base and ngpio into gpio_device")
    assumed that GPIO descriptors are either valid or error
    pointers, but gpiod_get_[index_]optional() actually return
    NULL descriptors and then all subsequent calls should just
    bail out.
    
    Cc: stable@vger.kernel.org
    Cc: Sergei Shtylyov <sergei.shtylyov@cogentembedded.com>
    Cc: Florian Fainelli <f.fainelli@gmail.com>
    Cc: Andrew Lunn <andrew@lunn.ch>
    Fixes: fdeb8e1547cb ("gpio: reflect base and ngpio into gpio_device")
    Reported-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 8b92e17efe029cc19f435f9fcbdfb1e7b9beb0ef
Author: Linus Walleij <linus.walleij@linaro.org>
Date:   Fri May 27 14:24:04 2016 +0200

    gpio: handle compatible ioctl() pointers
    
    If we're using the compatible ioctl() we need to handle the
    argument pointer in a special way or there will be trouble.
    
    Fixes: 3c702e9987e2 ("gpio: add a userspace chardev ABI for GPIOs")
    Reported-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
    Reviewed-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 9c10280d85c14a20751ab6c1185ad725172936d6
Author: Linus Walleij <linus.walleij@linaro.org>
Date:   Wed May 25 10:56:03 2016 +0200

    gpio: flush direction status in gpiochip_lock_as_irq()
    
    As irqchip and gpiochip functions are orthogonal, the IRQ
    set-up or something else can have changed the direction of
    the GPIO line from what the GPIO descriptor knows when we
    get into gpiochip_lock_as_irq(). Make sure to re-read the
    direction setting if we have the .get_direction() callback
    enabled for the chip.
    
    Else we get problems like this:
    
    iio iio:device2: interrupts on the rising edge
    gpio gpiochip2: (8012e080.gpio): gpiochip_lock_as_irq:
      tried to flag a GPIO set as output for IRQ
    gpio gpiochip2: (8012e080.gpio): unable to lock HW IRQ 0 for IRQ
    genirq: Failed to request resources for l3g4200d-trigger
      (irq 111) on irqchip nmk1-32-63
    iio iio:device2: failed to request trigger IRQ.
    st-gyro-i2c: probe of 2-0068 failed with error -22
    
    Fixes: 72d320006177 ("gpio: set up initial state from .get_direction()")
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 320a6480ef24b03655e1854bd01c9b0a8b8d4a3f
Author: Sylvain Lemieux <slemieux@tycoint.com>
Date:   Wed May 11 13:40:00 2016 -0400

    gpio: lpc32xx: disable broken to_irq support
    
    The "to_irq" functionality is broken inside this driver since commit
    76ba59f8366f ("genirq: Add irq_domain-aware core IRQ handler").
    
    The addition of the new lpc32xx irqchip driver in 4.7, fixed the
    lpc32xx platform interrupt issue.
    
    When switching to the new lpc32xx irqchip driver, a warning appear
    in the lpc32xx gpio driver: warning: "NR_IRQS" redefined.
    
    To remove this warning (temporary solution), this patch
    disables the broken "to_irq" mapping functionality support.
    
    Signed-off-by: Sylvain Lemieux <slemieux@tycoint.com>
    Acked-by: Vladimir Zapolskiy <vz@mleia.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit ab6a11a7c8ef47f996974dd3c648c2c0b1a36ab1
Author: Tom Lendacky <thomas.lendacky@amd.com>
Date:   Fri May 20 17:33:03 2016 -0500

    crypto: ccp - Fix AES XTS error for request sizes above 4096
    
    The ccp-crypto module for AES XTS support has a bug that can allow requests
    greater than 4096 bytes in size to be passed to the CCP hardware. The CCP
    hardware does not support request sizes larger than 4096, resulting in
    incorrect output. The request should actually be handled by the fallback
    mechanism instantiated by the ccp-crypto module.
    
    Add a check to insure the request size is less than or equal to the maximum
    supported size and use the fallback mechanism if it is not.
    
    Cc: <stable@vger.kernel.org> # 3.14.x-
    Signed-off-by: Tom Lendacky <thomas.lendacky@amd.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit cf0d44d513f275be9ce42158079d4257e8973889
Author: Michal Hocko <mhocko@suse.com>
Date:   Mon May 23 15:35:51 2016 +0200

    s390: fix info leak in do_sigsegv
    
    Aleksa has reported incorrect si_errno value when stracing task which
    received SIGSEGV:
    [pid 20799] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_errno=2510266, si_addr=0x100000000000000}
    
    The reason seems to be that do_sigsegv is not initializing siginfo
    structure defined on the stack completely so it will leak 4B of
    the previous stack content. Fix it simply by initializing si_errno
    to 0 (same as do_sigbus does already).
    
    Cc: stable # introduced pre-git times
    Reported-by: Aleksa Sarai <asarai@suse.de>
    Signed-off-by: Michal Hocko <mhocko@suse.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit e9bc15f28e5f0db44aba609780d6850eabefbf11
Author: Heiko Carstens <heiko.carstens@de.ibm.com>
Date:   Wed Jan 13 10:45:44 2016 +0100

    s390/config: update default configuration
    
    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit 787ab6e97024926f38773287d9f98a9b330bce23
Author: Hannes Reinecke <hare@suse.de>
Date:   Wed May 18 10:16:51 2016 +0200

    aacraid: do not activate events on non-SRC adapters
    
    Only SRC-based adapters support the AifReqEvent function, so there is no
    point in trying to activate it on older, non-SRC based adapters.  Doing
    so lead to crashes on older adapters.
    
    Signed-off-by: Hannes Reinecke <hare@suse.com>
    Reviewed-by: Johannes Thumshirn <jthumshirn@suse.com>
    Reviewed-by: Raghava Aditya Renukunta <RaghavaAaditya.Renukunta@microsemi.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit 7ebd67e0dece0ec53e5541fc600eda4e050fab72
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Thu May 12 23:37:38 2016 +0300

    mpt3sas: add missing curly braces
    
    There are some missing curly braces on this if statement, so we end up
    printing when we shouldn't.
    
    Fixes: a470a51cd648 ('mpt3sas: Handle active cable exception event')
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Acked-by: Chaitra P B <chaitra.basappa@broadcom.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit eb72d0bb84eee5d0dc3044fd17b75e7101dabb57
Author: Hannes Reinecke <hare@suse.de>
Date:   Tue Apr 26 08:06:58 2016 +0200

    sd: get disk reference in sd_check_events()
    
    sd_check_events() is called asynchronously, and might race
    with device removal. So always take a disk reference when
    processing the event to avoid the device being removed while
    the event is processed.
    
    Signed-off-by: Hannes Reinecke <hare@suse.de>
    Reviewed-by: Ewan D. Milne <emilne@redhat.com>
    Reviewed-by: Bart Van Assche <bart.vanassche@sandisk.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit a621bac3044ed6f7ec5fa0326491b2d4838bfa93
Author: James Bottomley <James.Bottomley@HansenPartnership.com>
Date:   Fri May 13 12:04:06 2016 -0700

    scsi_lib: correctly retry failed zero length REQ_TYPE_FS commands
    
    When SCSI was written, all commands coming from the filesystem
    (REQ_TYPE_FS commands) had data.  This meant that our signal for needing
    to complete the command was the number of bytes completed being equal to
    the number of bytes in the request.  Unfortunately, with the advent of
    flush barriers, we can now get zero length REQ_TYPE_FS commands, which
    confuse this logic because they satisfy the condition every time.  This
    means they never get retried even for retryable conditions, like UNIT
    ATTENTION because we complete them early assuming they're done.  Fix
    this by special casing the early completion condition to recognise zero
    length commands with errors and let them drop through to the retry code.
    
    Cc: stable@vger.kernel.org
    Reported-by: Sebastian Parschauer <s.parschauer@gmx.de>
    Signed-off-by: James E.J. Bottomley <jejb@linux.vnet.ibm.com>
    Tested-by: Jack Wang <jinpu.wang@profitbricks.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit bad6a185b4d6f81d0ed2b6e4c16307969f160b95
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 18 16:55:56 2016 +0200

    crypto: public_key: select CRYPTO_AKCIPHER
    
    In some rare randconfig builds, we can end up with
    ASYMMETRIC_PUBLIC_KEY_SUBTYPE enabled but CRYPTO_AKCIPHER disabled,
    which fails to link because of the reference to crypto_alloc_akcipher:
    
    crypto/built-in.o: In function `public_key_verify_signature':
    :(.text+0x110e4): undefined reference to `crypto_alloc_akcipher'
    
    This adds a Kconfig 'select' statement to ensure the dependency
    is always there.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit d462e32259810aaaf13440b033b99e1aad33eccd
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Wed May 18 13:39:05 2016 +0300

    crypto: omap-sham - potential Oops on error in probe
    
    This if statement is reversed so we end up either leaking or Oopsing on
    error.
    
    Fixes: dbe246209bc1 ('crypto: omap-sham - Use dma_request_chan() for requesting DMA channel')
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Acked-by: Peter Ujfalusi <peter.ujfalusi@ti.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit 6edf0aa4f8bbdfbb4d6d786892fa02728d05dc36
Author: Michael Holzheu <holzheu@linux.vnet.ibm.com>
Date:   Wed May 11 21:13:13 2016 +0200

    s390/bpf: fix recache skb->data/hlen for skb_vlan_push/pop
    
    In case of usage of skb_vlan_push/pop, in the prologue we store
    the SKB pointer on the stack and restore it after BPF_JMP_CALL
    to skb_vlan_push/pop.
    
    Unfortunately currently there are two bugs in the code:
    
     1) The wrong stack slot (offset 170 instead of 176) is used
     2) The wrong register (W1 instead of B1) is saved
    
    So fix this and use correct stack slot and register.
    
    Fixes: 9db7f2b81880 ("s390/bpf: recache skb->data/hlen for skb_vlan_push/pop")
    Cc: stable@vger.kernel.org # 4.3+
    Signed-off-by: Michael Holzheu <holzheu@linux.vnet.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit 0fa963553a5c28d8f8aabd8878326d3f782045fc
Author: Michael Holzheu <holzheu@linux.vnet.ibm.com>
Date:   Thu May 12 18:10:48 2016 +0200

    s390/bpf: reduce maximum program size to 64 KB
    
    The s390 BFP compiler currently uses relative branch instructions
    that only support jumps up to 64 KB. Examples are "j", "jnz", "cgrj",
    etc.  Currently the maximum size of s390 BPF programs is set
    to 0x7ffff.  If branches over 64 KB are generated the, kernel can
    crash due to incorrect code.
    
    So fix this an reduce the maximum size to 64 KB. Programs larger than
    that will be interpreted.
    
    Fixes: ce2b6ad9c185 ("s390/bpf: increase BPF_SIZE_MAX")
    
    Cc: stable@vger.kernel.org # 4.3+
    Signed-off-by: Michael Holzheu <holzheu@linux.vnet.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>