initramfs: fix a compilation error
754006569c54 ("initramfs: cleanup populate_rootfs") introduced a
compilation error with CONFIG_BLK_DEV_RAM != y due to clean_rootfs() is
only declared with CONFIG_BLK_DEV_RAM=y.

init/initramfs.c: In function 'populate_rootfs':
init/initramfs.c:659:3: error: implicit declaration of function
'clean_rootfs'; did you mean 'clean_path'?
[-Werror=implicit-function-declaration]
   clean_rootfs();
   ^~~~~~~~~~~~
   clean_path

Link: http://lkml.kernel.org/r/20190328014806.36375-1-cai@lca.pw
Signed-off-by: Qian Cai <cai@lca.pw>
Cc: Christoph Hellwig <hch@lst.de>
Cc: Mike Rapoport <rppt@linux.ibm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>