fixup: vmscan: Fix build on !CONFIG_MEMCG from nr_deactivate changes
"mm: move nr_deactivate accounting to shrink_active_list()" uses the
non-irqsaved version of count_memcg_events (__count_memcg_events), but
we've only exported the irqsaving version of it to userspace, so the build
breaks:

    mm/vmscan.c: In function `shrink_active_list':
    mm/vmscan.c:2101:2: error: implicit declaration of function `__count_memcg_events'; did you mean `count_memcg_events'? [-Werror=implicit-function-declaration]

This fixup makes it build with !CONFIG_MEMCG.

Link: http://lkml.kernel.org/r/20190322150513.GA22021@chrisdown.name
Signed-off-by: Chris Down <chris@chrisdown.name>
Cc: Kirill Tkhai <ktkhai@virtuozzo.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>