origin
GIT 3d661e2a2d1cf0ad1ce54d690f05e755da59e6c9

commit 2824f5033248600673e3e126a4d135363cbfd9ac
Author: Steven Rostedt (VMware) <rostedt@goodmis.org>
Date:   Mon May 28 10:56:36 2018 -0400

    tracing: Make the snapshot trigger work with instances
    
    The snapshot trigger currently only affects the main ring buffer, even when
    it is used by the instances. This can be confusing as the snapshot trigger
    is listed in the instance.
    
     > # cd /sys/kernel/tracing
     > # mkdir instances/foo
     > # echo snapshot > instances/foo/events/syscalls/sys_enter_fchownat/trigger
     > # echo top buffer > trace_marker
     > # echo foo buffer > instances/foo/trace_marker
     > # touch /tmp/bar
     > # chown rostedt /tmp/bar
     > # cat instances/foo/snapshot
     # tracer: nop
     #
     #
     # * Snapshot is freed *
     #
     # Snapshot commands:
     # echo 0 > snapshot : Clears and frees snapshot buffer
     # echo 1 > snapshot : Allocates snapshot buffer, if not already allocated.
     #                      Takes a snapshot of the main buffer.
     # echo 2 > snapshot : Clears snapshot buffer (but does not allocate or free)
     #                      (Doesn't have to be '2' works with any number that
     #                       is not a '0' or '1')
    
     > # cat snapshot
     # tracer: nop
     #
     #                              _-----=> irqs-off
     #                             / _----=> need-resched
     #                            | / _---=> hardirq/softirq
     #                            || / _--=> preempt-depth
     #                            ||| /     delay
     #           TASK-PID   CPU#  ||||    TIMESTAMP  FUNCTION
     #              | |       |   ||||       |         |
                 bash-1189  [000] ....   111.488323: tracing_mark_write: top buffer
    
    Not only did the snapshot occur in the top level buffer, but the instance
    snapshot buffer should have been allocated, and it is still free.
    
    Cc: stable@vger.kernel.org
    Fixes: 85f2b08268c01 ("tracing: Add basic event trigger framework")
    Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>

commit 86b389ff22bd6ad8fd3cb98e41cd271886c6d023
Author: Steven Rostedt (VMware) <rostedt@goodmis.org>
Date:   Sun May 27 20:54:44 2018 -0400

    tracing: Fix crash when freeing instances with event triggers
    
    If a instance has an event trigger enabled when it is freed, it could cause
    an access of free memory. Here's the case that crashes:
    
     # cd /sys/kernel/tracing
     # mkdir instances/foo
     # echo snapshot > instances/foo/events/initcall/initcall_start/trigger
     # rmdir instances/foo
    
    Would produce:
    
     general protection fault: 0000 [#1] PREEMPT SMP PTI
     Modules linked in: tun bridge ...
     CPU: 5 PID: 6203 Comm: rmdir Tainted: G        W         4.17.0-rc4-test+ #933
     Hardware name: Hewlett-Packard HP Compaq Pro 6300 SFF/339A, BIOS K01 v03.03 07/14/2016
     RIP: 0010:clear_event_triggers+0x3b/0x70
     RSP: 0018:ffffc90003783de0 EFLAGS: 00010286
     RAX: 0000000000000000 RBX: 6b6b6b6b6b6b6b2b RCX: 0000000000000000
     RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff8800c7130ba0
     RBP: ffffc90003783e00 R08: ffff8801131993f8 R09: 0000000100230016
     R10: ffffc90003783d80 R11: 0000000000000000 R12: ffff8800c7130ba0
     R13: ffff8800c7130bd8 R14: ffff8800cc093768 R15: 00000000ffffff9c
     FS:  00007f6f4aa86700(0000) GS:ffff88011eb40000(0000) knlGS:0000000000000000
     CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
     CR2: 00007f6f4a5aed60 CR3: 00000000cd552001 CR4: 00000000001606e0
     Call Trace:
      event_trace_del_tracer+0x2a/0xc5
      instance_rmdir+0x15c/0x200
      tracefs_syscall_rmdir+0x52/0x90
      vfs_rmdir+0xdb/0x160
      do_rmdir+0x16d/0x1c0
      __x64_sys_rmdir+0x17/0x20
      do_syscall_64+0x55/0x1a0
      entry_SYSCALL_64_after_hwframe+0x49/0xbe
    
    This was due to the call the clears out the triggers when an instance is
    being deleted not removing the trigger from the link list.
    
    Cc: stable@vger.kernel.org
    Fixes: 85f2b08268c01 ("tracing: Add basic event trigger framework")
    Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>

commit a30e7d1e37e8acc37c25420d93af218166cca3ae
Author: Vincent Chen <vincentc@andestech.com>
Date:   Mon May 21 14:36:22 2018 +0800

    nds32: Fix compiler warning, Wstringop-overflow, in vdso.c
    
    Getting a compiler warning, Wstringop-overflow, in
    arch/nds32/kernel/vdso.c when kernel is built by gcc-8. Declaring
    vdso_start and vdso_end as a pointer to fix this compiler warning.
    
    Signed-off-by: Vincent Chen <vincentc@andestech.com>
    Reviewed-by: Greentime Hu <greentime@andestech.com>
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit aaaaba57509526ce924f997d8690ee9e0c93945a
Author: Vincent Chen <vincentc@andestech.com>
Date:   Mon May 14 18:56:35 2018 +0800

    nds32: Disable local irq before calling cpu_dcache_wb_page in copy_user_highpage
    
    In order to ensure that all data in source page has been written back
    to memory before copy_page, the local irq shall be disabled before
    calling cpu_dcache_wb_page(). In addition, removing unneeded page
    invalidation for 'to' page.
    
    Signed-off-by: Vincent Chen <vincentc@andestech.com>
    Reviewed-by: Greentime Hu <greentime@andestech.com>
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit 5b9f95699b2166e06b7d7820c8173fdbff0ddf35
Author: Vincent Chen <vincentc@andestech.com>
Date:   Mon May 14 16:56:53 2018 +0800

    nds32: Flush the cache of the page at vmaddr instead of kaddr in flush_anon_page
    
    According to Documentation/cachetlb.txt, the cache of the page at vmaddr
    shall be flushed in flush_anon_page instead of the cache of the page at
    page_address(page).
    
    Signed-off-by: Vincent Chen <vincentc@andestech.com>
    Reviewed-by: Greentime Hu <greentime@andestech.com>
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit efcc4ea872edaeded28245d9b2ca8b9d8181b7cf
Author: Vincent Chen <vincentc@andestech.com>
Date:   Tue Apr 24 15:08:46 2018 +0800

    nds32: Correct flush_dcache_page function
    
    1. Disable local irq before d-cache write-back and invalidate.
       The cpu_dcache_wbinval_page function is composed of d-cache
    write-back and invalidate. If the local irq is enabled when calling
    cpu_dcache_wbinval_page, the content of d-cache is possibly updated
    between write-back and invalidate. In this case, the updated data will
    be dropped due to the following d-cache invalidation. Therefore, we
    disable the local irq before calling cpu_dcache_wbinval_page.
    
    2. Correct the data write-back for page aliasing case.
       Only the page whose (page->index << PAGE_SHIFT) is located at the
    same page color as page_address(page) needs to execute data write-back
    in flush_dcache_page function.
    
    Signed-off-by: Vincent Chen <vincentc@andestech.com>
    Reviewed-by: Greentime Hu <greentime@andestech.com>
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit 1613de8a785d21b3aac73d2a2e640b66d514393b
Author: Nickhu <nickhu@andestech.com>
Date:   Thu May 3 10:15:56 2018 +0800

    nds32: Fix the unaligned access handler
    
    If the kernel config 'CONFIG_ALIGNMENT_TRAP' and the file
    '/proc/sys/nds32/unaligned_access/enable' are set, the kernel
    unaligned access handler does not handle correctly when the
    value of immediate field is negative. This commit fixes the
    unaligned access handler in kernel.
    
    Signed-off-by: Nickhu <nickhu@andestech.com>
    Reviewed-by: Greentime Hu <greentime@andestech.com>
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit b3a75846a5cfbea137e2810b2bf9407141e70feb
Author: Nickhu <nickhu@andestech.com>
Date:   Fri May 4 16:40:11 2018 +0800

    nds32: Renaming the file for unaligned access
    
    Change the name of the file '/proc/sys/nds32/unaligned_acess'
    to '/proc/sys/nds32/unaligned_access'
    
    Signed-off-by: Nickhu <nickhu@andestech.com>
    Reviewed-by: Greentime Hu <greentime@andestech.com>
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit abb90a24eade1f612324de0e6920041ef64795cb
Author: Greentime Hu <greentime@andestech.com>
Date:   Mon Apr 30 15:02:27 2018 +0800

    nds32: To fix a cache inconsistency issue by setting correct cacheability of NTC
    
    The nds32 architecture will use physical memory when interrupt or
    exception comes and it will use the setting of NTC0-4. The original
    implementation didn't consider the DRAM start address may start from 1GB,
    2GB or 3GB to cause this issue. It will write the data to DRAM if it is
    running in physical address however kernel will read the data with
    virtaul address through data cache. In this case, the data of DRAM is
    latest.
    
    This fix will set the correct cacheability to let kernel write/read the
    latest data in cache instead of DRAM.
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit 8769c223491a7fbb345021e7004cbdffe024eaf8
Author: Greentime Hu <greentime@andestech.com>
Date:   Mon Apr 30 11:32:47 2018 +0800

    nds32: To refine readability of INT_MASK_INITAIAL_VAL
    
    Refine readability of INT_MASK_INITAIAL_VAL with meaningful macro instead
    of magic number.
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit 3ff2228dcea4e5c9b517375bd3aa9e3a1a3f29a0
Author: Greentime Hu <greentime@andestech.com>
Date:   Mon Apr 30 11:21:18 2018 +0800

    nds32: Fix the virtual address may map too much range by tlbop issue.
    
    We use tlbop to map virtual address in the first beginning, however it
    may map too much if DRAM size is not that big. We have to invalidate the
    mapping when the page table is created.
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit b3b112bb06eb26ce44af63d599aaf5fe54de0699
Author: Greentime Hu <greentime@andestech.com>
Date:   Thu Apr 19 16:26:43 2018 +0800

    nds32: Fix the allmodconfig build. To make sure CONFIG_CPU_LITTLE_ENDIAN is default y
    
    This way we can build kernel with CONFIG_CPU_LITTLE_ENDIAN=y. Build allmodconfig
    and allnoconfig are available too. It also fixes the endian mismatch issue
    because AFLAGS and LDFLAGS is not passed correctly.
    
    Signed-off-by: Vincent Ren-Wei Chen <vincentc@andestech.com>
    Signed-off-by: Greentime Hu <greentime@andestech.com>

commit c8c20f9c162da25ea0893d5c5ded3a89382a2b5e
Author: Greentime Hu <greentime@andestech.com>
Date:   Thu Apr 19 16:04:36 2018 +0800

    nds32: Fix build failed because arch_trace_hardirqs_off is changed to trace_hardirqs_off.
    
    It broke the 'allmodconfig' build when CONFIG_TRACE_IRQFLAGS is enabled.
    
    Signed-off-by: Nick Chun-Ming Hu <nickhu@andestech.com>
    Signed-off-by: Greentime Hu <greentime@andestech.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>

commit bb912671e36552e11352a6b749dcf68b0df6ad01
Author: Greentime Hu <greentime@andestech.com>
Date:   Thu Apr 19 15:59:38 2018 +0800

    nds32: Fix the unknown type u8 issue.
    
    It broke the 'allmodconfig' build.
    We need to include <linux/types.h> to make sure the type is defined
    before using it.
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>

commit e3f4624388731eb475ef7494b43440b3ad9269e1
Author: Greentime Hu <greentime@andestech.com>
Date:   Thu Apr 19 15:45:45 2018 +0800

    nds32: Fix the symbols undefined issue by exporting them.
    
    It broke the 'allmodconfig' build.
      LD      vmlinux
      SYSMAP  System.map
      Building modules, stage 2.
      MODPOST 5028 modules
    ERROR: "flush_dcache_page" [net/sunrpc/xprtrdma/rpcrdma.ko] undefined!
    ERROR: "empty_zero_page" [net/ceph/libceph.ko] undefined!
    ERROR: "save_stack_trace" [kernel/backtracetest.ko] undefined!
    ERROR: "clear_page" [fs/ocfs2/dlm/ocfs2_dlm.ko] undefined!
    ERROR: "copy_page" [fs/nilfs2/nilfs2.ko] undefined!
    ...
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>

commit 03969d0b3a3f6a7cd2c731eed1c4ccf76da88586
Author: Greentime Hu <greentime@andestech.com>
Date:   Thu Apr 19 15:38:58 2018 +0800

    nds32: Fix xfs_buf built failed by export invalidate_kernel_vmap_range and flush_kernel_vmap_range
    
    It broke the 'allmodconfig' build.
    fs/xfs/xfs_buf.c: In function 'xfs_buf_bio_end_io':
    fs/xfs/xfs_buf.c:1242:3: error: implicit declaration of function 'invalidate_kernel_vmap_range' [-Werror=implicit-function-declaration]
       invalidate_kernel_vmap_range(bp->b_addr, xfs_buf_vmap_len(bp));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fs/xfs/xfs_buf.c: In function 'xfs_buf_ioapply_map':
    fs/xfs/xfs_buf.c:1312:4: error: implicit declaration of function 'flush_kernel_vmap_range' [-Werror=implicit-function-declaration]
        flush_kernel_vmap_range(bp->b_addr,
        ^~~~~~~~~~~~~~~~~~~~~~~
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>

commit 8cedb78fdf82468020a2f3b24ef63ccd397662a2
Author: Greentime Hu <greentime@andestech.com>
Date:   Thu Apr 19 11:33:01 2018 +0800

    nds32: Fix drivers/gpu/drm/udl/udl_fb.c building error by defining PAGE_SHARED
    
    It broke the 'allmodconfig' build.
    drivers/gpu/drm/udl/udl_fb.c: In function 'udl_fb_mmap':
    drivers/gpu/drm/udl/udl_fb.c:183:52: error: 'PAGE_SHARED' undeclared (first use in this function)
       if (remap_pfn_range(vma, start, page, PAGE_SIZE, PAGE_SHARED))
                                                        ^~~~~~~~~~~
    drivers/gpu/drm/udl/udl_fb.c:183:52: note: each undeclared identifier is reported only once for each function it appears in
    make[4]: *** [drivers/gpu/drm/udl/udl_fb.o] Error 1
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>

commit 81560e011a3420db03f7b021d1bc37a2242634f7
Author: Greentime Hu <greentime@andestech.com>
Date:   Thu Apr 19 11:27:59 2018 +0800

    nds32: Fix building error of crypto/xor.c by adding xor.h
    
    When I compiled with allmodconfig, it caused this building failed.
    crypto/xor.c:25:21: fatal error: asm/xor.h: No such file or directory
     #include <asm/xor.h>
                         ^
    compilation terminated.
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>

commit 6ca4b262dbc94b3ed5fd4c8c1ad4d86616286779
Author: Greentime Hu <greentime@andestech.com>
Date:   Thu Apr 19 11:17:35 2018 +0800

    nds32: Fix building error when CONFIG_FREEZE is enabled.
    
    To include kernel/Kconfig.freezer to make sure the dependency between
    CONFIG_CGROUP_FREEZER and CONFIG_FREEZER
    
    It will cause building error when I make allmodconfig.
    
    kernel/cgroup/freezer.c: In function 'freezer_css_online':
    kernel/cgroup/freezer.c:116:15: error: 'system_freezing_cnt' undeclared (first use in this function)
       atomic_inc(&system_freezing_cnt);
                   ^~~~~~~~~~~~~~~~~~~
    kernel/cgroup/freezer.c:116:15: note: each undeclared identifier is reported only once for each function it appears in
    kernel/cgroup/freezer.c: In function 'freezer_css_offline':
    kernel/cgroup/freezer.c:137:15: error: 'system_freezing_cnt' undeclared (first use in this function)
       atomic_dec(&system_freezing_cnt);
                   ^~~~~~~~~~~~~~~~~~~
    kernel/cgroup/freezer.c: In function 'freezer_attach':
    kernel/cgroup/freezer.c:181:4: error: implicit declaration of function 'freeze_task' [-Werror=implicit-function-declaration]
        freeze_task(task);
        ^~~~~~~~~~~
    kernel/cgroup/freezer.c: In function 'freezer_apply_state':
    kernel/cgroup/freezer.c:360:16: error: 'system_freezing_cnt' undeclared (first use in this function)
        atomic_inc(&system_freezing_cnt);
                    ^~~~~~~~~~~~~~~~~~~
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>

commit aeaa7af744fadf5fa03bdea2d12ecc0fa2a41542
Author: Greentime Hu <greentime@andestech.com>
Date:   Thu Apr 19 11:06:31 2018 +0800

    nds32: lib: To use generic lib instead of libgcc to prevent the symbol undefined issue.
    
    We can use the generic lib to fix these error because the symbol of
    libgcc in toolchain is not exported.
    
    ERROR: "__ucmpdi2" [fs/xfs/xfs.ko] undefined!
    ERROR: "__ashrdi3" [fs/xfs/xfs.ko] undefined!
    ERROR: "__lshrdi3" [fs/xfs/xfs.ko] undefined!
    ERROR: "__ashldi3" [fs/ntfs/ntfs.ko] undefined!
    ...
    
    Signed-off-by: Greentime Hu <greentime@andestech.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>