origin
GIT 9ffc59d57228d74809700be6f7ecb1db10292f05

commit 3ed1d012ac3e60e0e95cda6fbd59352ec6dcbb88
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sat Jun 16 17:09:41 2018 -0700

    Fix Documentation build due to rename of main.c to mtrr.c
    
    This fixes this documentation build error that is due to a file rename:
    
      Error: Cannot open file ../arch/x86/kernel/cpu/mtrr/main.c
    
    Fixes: 0afe832e55a7 ("Merge branch 'x86-cleanups-for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/tip/tip")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit b23908d3c48a37c46c6a26df2cdeab1610b360ba
Author: Simon Glass <sjg@chromium.org>
Date:   Sun Jun 17 14:09:42 2018 +0200

    firmware: dmi: Add access to the SKU ID string
    
    This is used in some systems from user space for determining the identity
    of the device.
    
    Expose this as a file so that that user-space tools don't need to read
    from /sys/firmware/dmi/tables/DMI
    
    Signed-off-by: Simon Glass <sjg@chromium.org>
    Signed-off-by: Jean Delvare <jdelvare@suse.de>

commit 83ffdeadb46b61580c4c9a5319bd76d258a2963d
Author: Paulo Alcantara <paulo@paulo.ac>
Date:   Fri Jun 15 15:58:00 2018 -0300

    cifs: Fix invalid check in __cifs_calc_signature()
    
    The following check would never evaluate to true:
      > if (i == 0 && iov[0].iov_len <= 4)
    
    Because 'i' always starts at 1.
    
    This patch fixes it and also move the header checks outside the for loop
    - which makes more sense.
    
    Signed-off-by: Paulo Alcantara <palcantara@suse.de>
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit 35e2cc1ba755cf9dbd042e308b2928c868767a98
Author: Paulo Alcantara <paulo@paulo.ac>
Date:   Fri Jun 15 10:22:44 2018 -0300

    cifs: Use correct packet length in SMB2_TRANSFORM header
    
    In smb3_init_transform_rq(), 'orig_len' was only counting the request
    length, but forgot to count any data pages in the request.
    
    Writing or creating files with the 'seal' mount option was broken.
    
    In addition, do some code refactoring by exporting smb2_rqst_len() to
    calculate the appropriate packet size and avoid duplicating the same
    calculation all over the code.
    
    The start of the io vector is either the rfc1002 length (4 bytes) or a
    SMB2 header which is always > 4. Use this fact to check and skip the
    rfc1002 length if requested.
    
    Signed-off-by: Paulo Alcantara <palcantara@suse.de>
    Reviewed-by: Aurelien Aptel <aaptel@suse.com>
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit d819d298c7258849d56eb400be436aff3ba2aae2
Author: Steve French <stfrench@microsoft.com>
Date:   Thu Jun 14 22:30:56 2018 -0500

    smb3: fix corrupt path in subdirs on smb311 with posix
    
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit 115d5d288dc3368e3d6e7eb9ee213b342f072c23
Author: Steve French <stfrench@microsoft.com>
Date:   Thu Jun 14 21:59:31 2018 -0500

    smb3: do not display empty interface list
    
    If server does not support listing interfaces then do not
    display empty "Server interfaces" line to avoid confusing users.
    
    Signed-off-by: Steve French <stfrench@microsoft.com>
    CC: Aurelien Aptel <aaptel@suse.com>

commit bea851b8babe6c87c36e97c9de0dd0bea0dd5802
Author: Steve French <stfrench@microsoft.com>
Date:   Thu Jun 14 21:56:32 2018 -0500

    smb3: Fix mode on mkdir on smb311 mounts
    
    mkdir was not passing the mode on smb3.11 mounts with posix extensions
    
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit 662bf5bc0a6f7b2abf7f9125c6319f06bb2efcf9
Author: Paulo Alcantara <paulo@paulo.ac>
Date:   Thu Jun 14 17:34:08 2018 -0300

    cifs: Fix kernel oops when traceSMB is enabled
    
    When traceSMB is enabled through 'echo 1 > /proc/fs/cifs/traceSMB', after a
    mount, the following oops is triggered:
    
    [   27.137943] BUG: unable to handle kernel paging request at
    ffff8800f80c268b
    [   27.143396] PGD 2c6b067 P4D 2c6b067 PUD 0
    [   27.145386] Oops: 0000 [#1] SMP PTI
    [   27.146186] CPU: 2 PID: 2655 Comm: mount.cifs Not tainted 4.17.0+ #39
    [   27.147174] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS
    1.0.0-prebuilt.qemu-project.org 04/01/2014
    [   27.148969] RIP: 0010:hex_dump_to_buffer+0x413/0x4b0
    [   27.149738] Code: 48 8b 44 24 08 31 db 45 31 d2 48 89 6c 24 18 44 89
    6c 24 24 48 c7 c1 78 b5 23 82 4c 89 64 24 10 44 89 d5 41 89 dc 4c 8d 58
    02 <44> 0f b7 00 4d 89 dd eb 1f 83 c5 01 41 01 c4 41 39 ef 0f 84 48 fe
    [   27.152396] RSP: 0018:ffffc9000058f8c0 EFLAGS: 00010246
    [   27.153129] RAX: ffff8800f80c268b RBX: 0000000000000000 RCX:
    ffffffff8223b578
    [   27.153867] RDX: 0000000000000000 RSI: ffffffff81a55496 RDI:
    0000000000000008
    [   27.154612] RBP: 0000000000000000 R08: 0000000000000020 R09:
    0000000000000083
    [   27.155355] R10: 0000000000000000 R11: ffff8800f80c268d R12:
    0000000000000000
    [   27.156101] R13: 0000000000000002 R14: ffffc9000058f94d R15:
    0000000000000008
    [   27.156838] FS:  00007f1693a6b740(0000) GS:ffff88007fd00000(0000)
    knlGS:0000000000000000
    [   27.158354] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
    [   27.159093] CR2: ffff8800f80c268b CR3: 00000000798fa001 CR4:
    0000000000360ee0
    [   27.159892] DR0: 0000000000000000 DR1: 0000000000000000 DR2:
    0000000000000000
    [   27.160661] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7:
    0000000000000400
    [   27.161464] Call Trace:
    [   27.162123]  print_hex_dump+0xd3/0x160
    [   27.162814] journal-offline (2658) used greatest stack depth: 13144
    bytes left
    [   27.162824]  ? __release_sock+0x60/0xd0
    [   27.165344]  ? tcp_sendmsg+0x31/0x40
    [   27.166177]  dump_smb+0x39/0x40
    [   27.166972]  ? vsnprintf+0x236/0x490
    [   27.167807]  __smb_send_rqst.constprop.12+0x103/0x430
    [   27.168554]  ? apic_timer_interrupt+0xa/0x20
    [   27.169306]  smb_send_rqst+0x48/0xc0
    [   27.169984]  cifs_send_recv+0xda/0x420
    [   27.170639]  SMB2_negotiate+0x23d/0xfa0
    [   27.171301]  ? vsnprintf+0x236/0x490
    [   27.171961]  ? smb2_negotiate+0x19/0x30
    [   27.172586]  smb2_negotiate+0x19/0x30
    [   27.173257]  cifs_negotiate_protocol+0x70/0xd0
    [   27.173935]  ? kstrdup+0x43/0x60
    [   27.174551]  cifs_get_smb_ses+0x295/0xbe0
    [   27.175260]  ? lock_timer_base+0x67/0x80
    [   27.175936]  ? __internal_add_timer+0x1a/0x50
    [   27.176575]  ? add_timer+0x10f/0x230
    [   27.177267]  cifs_mount+0x101/0x1190
    [   27.177940]  ? cifs_smb3_do_mount+0x144/0x5c0
    [   27.178575]  cifs_smb3_do_mount+0x144/0x5c0
    [   27.179270]  mount_fs+0x35/0x150
    [   27.179930]  vfs_kern_mount.part.28+0x54/0xf0
    [   27.180567]  do_mount+0x5ad/0xc40
    [   27.181234]  ? kmem_cache_alloc_trace+0xed/0x1a0
    [   27.181916]  ksys_mount+0x80/0xd0
    [   27.182535]  __x64_sys_mount+0x21/0x30
    [   27.183220]  do_syscall_64+0x4e/0x100
    [   27.183882]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
    [   27.184535] RIP: 0033:0x7f169339055a
    [   27.185192] Code: 48 8b 0d 41 d9 2b 00 f7 d8 64 89 01 48 83 c8 ff c3
    66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 49 89 ca b8 a5 00 00 00 0f
    05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 0e d9 2b 00 f7 d8 64 89 01 48
    [   27.187268] RSP: 002b:00007fff7b44eb58 EFLAGS: 00000202 ORIG_RAX:
    00000000000000a5
    [   27.188515] RAX: ffffffffffffffda RBX: 00007f1693a7e70e RCX:
    00007f169339055a
    [   27.189244] RDX: 000055b9f97f64e5 RSI: 000055b9f97f652c RDI:
    00007fff7b45074f
    [   27.189974] RBP: 000055b9fb8c9260 R08: 000055b9fb8ca8f0 R09:
    0000000000000000
    [   27.190721] R10: 0000000000000000 R11: 0000000000000202 R12:
    000055b9fb8ca8f0
    [   27.191429] R13: 0000000000000000 R14: 00007f1693a7c000 R15:
    00007f1693a7e91d
    [   27.192167] Modules linked in:
    [   27.192797] CR2: ffff8800f80c268b
    [   27.193435] ---[ end trace 67404c618badf323 ]---
    
    The problem was that dump_smb() had been called with an invalid pointer,
    that is, in __smb_send_rqst(), iov[1] doesn't exist (n_vec == 1).
    
    This patch fixes it by relying on the n_vec value to dump out the smb
    packets.
    
    Signed-off-by: Paulo Alcantara <palcantara@suse.de>
    Signed-off-by: Steve French <stfrench@microsoft.com>
    Reviewed-by: Ronnie Sahlberg <lsahlber@redhat.com>

commit bc0fe8b207a14a6d7ecf8812edb92c8bdd5c9b2d
Author: Aurelien Aptel <aaptel@suse.com>
Date:   Thu Jun 14 15:43:20 2018 +0200

    CIFS: dump every session iface info
    
    Signed-off-by: Aurelien Aptel <aaptel@suse.com>
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit fe856be475f7cf5ffcde57341d175ce9fd09434b
Author: Aurelien Aptel <aaptel@suse.com>
Date:   Thu Jun 14 17:04:51 2018 +0200

    CIFS: parse and store info on iface queries
    
    Signed-off-by: Aurelien Aptel <aaptel@suse.com>
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit b6f0dd5d75f9689d57c7ea49e52c80cabb876cb4
Author: Aurelien Aptel <aaptel@suse.com>
Date:   Thu Jun 14 15:43:18 2018 +0200

    CIFS: add iface info to struct cifs_ses
    
    Signed-off-by: Aurelien Aptel <aaptel@suse.com>
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit bead042cccca5a7c5626b851b66a30698aa0ac36
Author: Aurelien Aptel <aaptel@suse.com>
Date:   Thu Jun 14 15:43:17 2018 +0200

    CIFS: complete PDU definitions for interface queries
    
    Signed-off-by: Aurelien Aptel <aaptel@suse.com>
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit e2292430c49dbbe2d54438a4c05dd937a8eeecdd
Author: Aurelien Aptel <aaptel@suse.com>
Date:   Thu Jun 14 15:43:16 2018 +0200

    CIFS: move default port definitions to cifsglob.h
    
    Signed-off-by: Aurelien Aptel <aaptel@suse.com>
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit cd2dca60be6f4742b63373fd7e4b445c8a634e51
Author: Paulo Alcantara <paulo@paulo.ac>
Date:   Wed Jun 13 13:54:14 2018 -0300

    cifs: Fix encryption/signing
    
    Since the rfc1002 generation was moved down to __smb_send_rqst(),
    the transform header is now in rqst->rq_iov[0].
    
    Correctly assign the transform header pointer in crypt_message().
    
    Signed-off-by: Paulo Alcantara <palcantara@suse.de>
    Reviewed-by: Ronnie Sahlberg <lsahlber@redhat.com>
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit 07cd952f3ad51bc7f87dcdba0faac979ee559fd3
Author: Ronnie Sahlberg <lsahlber@redhat.com>
Date:   Tue Jun 12 08:01:00 2018 +1000

    cifs: update __smb_send_rqst() to take an array of requests
    
    Signed-off-by: Ronnie Sahlberg <lsahlber@redhat.com>
    Signed-off-by: Steve French <smfrench@gmail.com>

commit 40eff45b5dc7df73fc8926c9bd81bde2d4c8ccca
Author: Ronnie Sahlberg <lsahlber@redhat.com>
Date:   Tue Jun 12 08:00:59 2018 +1000

    cifs: remove smb2_send_recv()
    
    Now that we have the plumbing to pass request without an rfc1002
    header all the way down to the point we write to the socket we no
    longer need the smb2_send_recv() function.
    
    Signed-off-by: Ronnie Sahlberg <lsahlber@redhat.com>
    Signed-off-by: Steve French <smfrench@gmail.com>

commit c713c8770fa5bfbeaac088cc7b959c7a6ba79f93
Author: Ronnie Sahlberg <lsahlber@redhat.com>
Date:   Tue Jun 12 08:00:58 2018 +1000

    cifs: push rfc1002 generation down the stack
    
    Move the generation of the 4 byte length field down the stack and
    generate it immediately before we start writing the data to the socket.
    
    Signed-off-by: Ronnie Sahlberg <lsahlber@redhat.com>
    Signed-off-by: Aurelien Aptel <aaptel@suse.com>
    Signed-off-by: Steve French <smfrench@gmail.com>

commit d409014e4feeab486fb36b350abfc4c94de8be37
Author: Steve French <stfrench@microsoft.com>
Date:   Wed Jun 13 17:05:58 2018 -0500

    smb3: increase initial number of credits requested to allow write
    
    Compared to other clients the Linux smb3 client ramps up
    credits very slowly, taking more than 128 operations before a
    maximum size write could be sent (since the number of credits
    requested is only 2 per small operation, causing the credit
    limit to grow very slowly).
    
    This lack of credits initially would impact large i/o performance,
    when large i/o is tried early before enough credits are built up.
    
    Signed-off-by: Steve French <stfrench@gmail.com>
    Reviewed-by: Ronnie Sahlberg <lsahlber@redhat.com>

commit 290c3982f66ab750e85863efcb1fdd736985e5d2
Author: Steve French <stfrench@microsoft.com>
Date:   Wed Jun 13 16:46:56 2018 -0500

    cifs: minor documentation updates
    
    Various minor cifs/smb3 documentation updates
    
    Signed-off-by: Steve French <stfrench@microsoft.com>
    Reviewed-by: Ronnie Sahlberg <lsahlber@redhat.com>

commit a93864d93977b99bda6c348a09b90a3d7ef8db3a
Author: Ronnie Sahlberg <lsahlber@redhat.com>
Date:   Thu Jun 14 06:48:35 2018 +1000

    cifs: add lease tracking to the cached root fid
    
    Use a read lease for the cached root fid so that we can detect
    when the content of the directory changes (via a break) at which time
    we close the handle. On next access to the root the handle will be reopened
    and cached again.
    
    Signed-off-by: Ronnie Sahlberg <lsahlber@redhat.com>
    Signed-off-by: Steve French <stfrench@microsoft.com>

commit 2fbb56446fde14a80790de9b182ae6f7c36a039a
Author: Steve French <smfrench@gmail.com>
Date:   Tue Jun 12 12:11:31 2018 -0500

    smb3: note that smb3.11 posix extensions mount option is experimental
    
    Signed-off-by: Steve French <stfrench@microsoft.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>