memblock-stop-using-implicit-alignement-to-smp_cache_bytes-checkpatch-fixes
ERROR: code indent should use tabs where possible
#244: FILE: arch/alpha/kernel/core_wildfire.c:114:
+        hose->sg_isa = iommu_arena_new(hose, 0x00800000, 0x00800000,$

WARNING: please, no spaces at the start of a line
#244: FILE: arch/alpha/kernel/core_wildfire.c:114:
+        hose->sg_isa = iommu_arena_new(hose, 0x00800000, 0x00800000,$

ERROR: code indent should use tabs where possible
#246: FILE: arch/alpha/kernel/core_wildfire.c:116:
+        hose->sg_pci = iommu_arena_new(hose, 0xc0000000, 0x08000000,$

WARNING: please, no spaces at the start of a line
#246: FILE: arch/alpha/kernel/core_wildfire.c:116:
+        hose->sg_pci = iommu_arena_new(hose, 0xc0000000, 0x08000000,$

ERROR: space required after that ';' (ctx:VxV)
#380: FILE: arch/ia64/kernel/mca.c:366:
+		(ia64_err_rec_t *)memblock_alloc(size, SMP_CACHE_BYTES);}
 		                                                       ^

WARNING: line over 80 characters
#822: FILE: mm/percpu.c:1104:
+	chunk = memblock_alloc(sizeof(struct pcpu_chunk) + BITS_TO_LONGS(region_size >> PAGE_SHIFT),

WARNING: line over 80 characters
#837: FILE: mm/percpu.c:1116:
+	chunk->alloc_map = memblock_alloc(BITS_TO_LONGS(region_bits) * sizeof(chunk->alloc_map[0]),

WARNING: line over 80 characters
#839: FILE: mm/percpu.c:1118:
+	chunk->bound_map = memblock_alloc(BITS_TO_LONGS(region_bits + 1) * sizeof(chunk->bound_map[0]),

WARNING: line over 80 characters
#841: FILE: mm/percpu.c:1120:
+	chunk->md_blocks = memblock_alloc(pcpu_chunk_nr_blocks(chunk) * sizeof(chunk->md_blocks[0]),

total: 3 errors, 6 warnings, 618 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/memblock-stop-using-implicit-alignement-to-smp_cache_bytes.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Mike Rapoport <rppt@linux.vnet.ibm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>