mm-add-support-for-pud-sized-transparent-hugepages-fix
include/linux/huge_mm.h: In function 'pud_trans_huge_lock':
include/linux/huge_mm.h:175: error: implicit declaration of function 'pud_devmap'

breaks bisectability

Cc: Dan Williams <dan.j.williams@intel.com>
Cc: Jan Kara <jack@suse.cz>
Cc: Kirill A. Shutemov <kirill.shutemov@linux.intel.com>
Cc: Matthew Wilcox <willy@linux.intel.com>
Cc: Ross Zwisler <ross.zwisler@linux.intel.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>