rbtree-avoid-generating-code-twice-for-the-cached-versions-checkpatch-fixes
WARNING: 'implemntation' may be misspelled - perhaps 'implementation'?
#8: 
rb_leftmost was wired deeper into the implemntation, but there were some

ERROR: Macros with complex values should be enclosed in parentheses
#180: FILE: include/linux/rbtree.h:130:
+#define RB_ROOT_CACHED (struct rb_root_cached) { {NULL, }, NULL }

ERROR: Macros with complex values should be enclosed in parentheses
#183: FILE: include/linux/rbtree.h:133:
+#define rb_first_cached(root) (root)->rb_leftmost

ERROR: code indent should use tabs where possible
#197: FILE: include/linux/rbtree.h:147:
+        if (root->rb_leftmost == node)$

WARNING: please, no spaces at the start of a line
#197: FILE: include/linux/rbtree.h:147:
+        if (root->rb_leftmost == node)$

ERROR: code indent should use tabs where possible
#198: FILE: include/linux/rbtree.h:148:
+                root->rb_leftmost = rb_next(node);$

WARNING: please, no spaces at the start of a line
#198: FILE: include/linux/rbtree.h:148:
+                root->rb_leftmost = rb_next(node);$

total: 4 errors, 3 warnings, 246 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/rbtree-avoid-generating-code-twice-for-the-cached-versions.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Michel Lespinasse <walken@google.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>