mm: fix compilation issue in kmap_flush_unused
Fengguang has reported the following compilation issue:
mm/highmem.c: In function 'kmap_flush_unused':
mm/highmem.c:157:8: error: void value not ignored as it ought to be
mm/highmem.c:158:15: error: 'PKMAP_INVALID_INDEX' undeclared (first use in this function)
mm/highmem.c:158:15: note: each undeclared identifier is reported only once for each function it appears in

The problem has been introduced by me (and it is specific to this tree)
when reverting 1918c826 (mm, highmem: makes flush_all_zero_pkmaps()
return index of last flushed entry).

Signed-off-by: Michal Hocko <mhocko@suse.cz>