origin
GIT b824a957bfb3f7f5ab2f7216239882f9092d2c27

commit 028402d4bcfd3e99421504674cc41b0cd32768c8
Author: Jordan Crouse <jcrouse@codeaurora.org>
Date:   Mon Feb 6 10:39:29 2017 -0700

    drm/msm: Make sure to detach the MMU during GPU cleanup
    
    We should be detaching the MMU before destroying the address
    space. To do this cleanly, the detach has to happen in
    adreno_gpu_cleanup() because it needs access to structs
    in adreno_gpu.c.  Plus it is better symmetry to have
    the attach and detach at the same code level.
    
    Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>
    Signed-off-by: Rob Clark <robdclark@gmail.com>

commit d322a693f585832130c3d09f2175b8f2b3ae99e1
Author: Vinay Simha BN <simhavcs@gmail.com>
Date:   Tue Mar 14 10:55:56 2017 +0530

    drm/msm/hdmi: redefinitions of macros not required
    
    4 macros already defined in hdmi.h,
    which is not required to redefine in hdmi_audio.c
    
    Signed-off-by: Vinay Simha BN <simhavcs@gmail.com>
    Signed-off-by: Rob Clark <robdclark@gmail.com>

commit 30512040ed8e1982e5ba16bb3e3a7f000ff65427
Author: Archit Taneja <architt@codeaurora.org>
Date:   Fri Mar 17 09:09:48 2017 +0530

    drm/msm/mdp5: Update SSPP_MAX value
    
    'SSPP_MAX + 1' is the max number of hwpipes that can be present on a
    MDP5 platform. Recently, 2 new cursor hwpipes were added, which
    caused overflows in arrays that used SSPP_MAX to represent the number
    of elements. Update the SSPP_MAX value to incorporate the extra
    hwpipes.
    
    Signed-off-by: Archit Taneja <architt@codeaurora.org>
    Signed-off-by: Rob Clark <robdclark@gmail.com>

commit a5fef535c529b64b622f9d7eafb3ab86850f5f8f
Author: Archit Taneja <architt@codeaurora.org>
Date:   Thu Feb 16 16:29:04 2017 +0530

    drm/msm/dsi: Fix bug in dsi_mgr_phy_enable
    
    A recent commit introduces a bug in dsi_mgr_phy_enable. In the non
    dual DSI mode, we reset the mdsi (master DSI) PHY. This isn't right
    since master and slave DSI exist only in dual DSI mode. For the normal
    mode of operation, we should simply reset the PHY of the DSI device
    (i.e. msm_dsi) corresponding to the current bridge.
    
    Usage of the wrong DSI pointer also resulted in a static checker
    warning. That too is resolved with this fix.
    
    Fixes: b62aa70a98c5 (drm/msm/dsi: Move PHY operations out of host)
    
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Archit Taneja <architt@codeaurora.org>
    Reviewed-by: Rob Clark <robdclark@gmail.com>
    Signed-off-by: Rob Clark <robdclark@gmail.com>

commit 1a5dff5d74e55608a9632a1d030bb79196e0755c
Author: Jordan Crouse <jcrouse@codeaurora.org>
Date:   Tue Mar 7 10:02:51 2017 -0700

    drm/msm: Don't allow zero sized buffer objects
    
    Zero sized buffer objects tend to make various bits of the GEM
    infrastructure complain:
    
     WARNING: CPU: 1 PID: 2323 at drivers/gpu/drm/drm_mm.c:389 drm_mm_insert_node_generic+0x258/0x2f0
     Modules linked in:
    
     CPU: 1 PID: 2323 Comm: drm-api-test Tainted: G        W 4.9.0-rc4-00906-g693af44 #213
     Hardware name: Qualcomm Technologies, Inc. DB820c (DT)
     task: ffff8000d7353400 task.stack: ffff8000d7720000
     PC is at drm_mm_insert_node_generic+0x258/0x2f0
     LR is at drm_vma_offset_add+0x4c/0x70
    
    Zero sized buffers serve no appreciable value to the user so disallow
    them at create time.
    
    Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>
    Signed-off-by: Rob Clark <robdclark@gmail.com>

commit f456d348b6320a2597a3f1fff3ad0011c5678603
Author: Jordan Crouse <jcrouse@codeaurora.org>
Date:   Tue Mar 7 09:50:27 2017 -0700

    drm/msm: Fix wrong pointer check in a5xx_destroy
    
    Instead of checking for a5xx_gpu->gpmu_iova during destroy we
    accidently check a5xx_gpu->gpmu_bo.
    
    Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>
    Signed-off-by: Rob Clark <robdclark@gmail.com>

commit 280489daa68bd20364b322c11e3f429a0212c611
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 13 17:43:48 2017 +0100

    drm/msm: adreno: fix build error without debugfs
    
    The newly added a5xx support fails to build when debugfs is diabled:
    
    drivers/gpu/drm/msm/adreno/a5xx_gpu.c:849:4: error: 'struct msm_gpu_funcs' has no member named 'show'
    drivers/gpu/drm/msm/adreno/a5xx_gpu.c:849:11: error: 'a5xx_show' undeclared here (not in a function); did you mean 'a5xx_irq'?
    
    This adds a missing #ifdef.
    
    Fixes: b5f103ab98c7 ("drm/msm: gpu: Add A5XX target support")
    Cc: stable@vger.kernel.org
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Rob Clark <robdclark@gmail.com>

commit 921d701e6f31e1ffaca3560416af1aa04edb4c4f
Author: Tobias Klauser <tklauser@distanz.ch>
Date:   Sun Apr 2 20:08:04 2017 -0700

    nios2: reserve boot memory for device tree
    
    Make sure to reserve the boot memory for the flattened device tree.
    Otherwise it might get overwritten, e.g. when initial_boot_params is
    copied, leading to a corrupted FDT and a boot hang/crash:
    
      bootconsole [early0] enabled
      Early console on uart16650 initialized at 0xf8001600
      OF: fdt: Error -11 processing FDT
      Kernel panic - not syncing: setup_cpuinfo: No CPU found in devicetree!
    
      ---[ end Kernel panic - not syncing: setup_cpuinfo: No CPU found in devicetree!
    
    Guenter Roeck says:
    
    > I think I found the problem. In unflatten_and_copy_device_tree(), with added
    > debug information:
    >
    > OF: fdt: initial_boot_params=c861e400, dt=c861f000 size=28874 (0x70ca)
    >
    > ... and then initial_boot_params is copied to dt, which results in corrupted
    > fdt since the memory overlaps. Looks like the initial_boot_params memory
    > is not reserved and (re-)allocated by early_init_dt_alloc_memory_arch().
    
    Cc: stable@vger.kernel.org
    Reported-by: Guenter Roeck <linux@roeck-us.net>
    Reference: http://lkml.kernel.org/r/20170226210338.GA19476@roeck-us.net
    Tested-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
    Acked-by: Ley Foon Tan <ley.foon.tan@intel.com>

commit 1493aa65ad076293722908f03bab3d4bf3dc3638
Author: Max Filippov <jcmvbkbc@gmail.com>
Date:   Fri Mar 31 16:26:21 2017 -0700

    xtensa: wire up statx system call
    
    Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>

commit e640cc306388b6f9dc8109d5c5d0550d7e69e5f7
Author: Max Filippov <jcmvbkbc@gmail.com>
Date:   Fri Mar 31 15:58:40 2017 -0700

    xtensa: fix stack dump output
    
    Use %pB in pr_cont format string instead of calling print_symbol
    separately. It turns
    
      [   19.166249] Call Trace:
      [   19.167265]  [<a000e50a>]
      [   19.167843]  __warn+0x92/0xa0
      [   19.169656]  [<a000e554>]
      [   19.170059]  warn_slowpath_fmt+0x3c/0x40
      [   19.171934]  [<a02d5bd8>]
    
    back into
    
      [   18.123240] Call Trace:
      [   18.125039]  [<a000e4f6>] __warn+0x92/0xa0
      [   18.126961]  [<a000e540>] warn_slowpath_fmt+0x3c/0x40
    
    Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>

commit 2b83878dd74a7c73bedcb6600663c1c46836e8af
Author: Max Filippov <jcmvbkbc@gmail.com>
Date:   Wed Mar 29 15:44:47 2017 -0700

    xtensa: make __pa work with uncached KSEG addresses
    
    When __pa is applied to virtual address in uncached KSEG region the
    result is incorrect. Fix it by checking if the original address is in
    the uncached KSEG and adjusting the result. It looks better than masking
    off bits because pfn_valid would correctly work with new __pa results
    and it may be made working in noMMU case, once we get definition for
    uncached memory view.
    
    This is required for the dma_common_mmap and DMA debug code to work
    correctly: they both indirectly use __pa with coherent DMA addresses.
    In case of DMA debug the visible effect is false reports that an address
    mapped for DMA is accessed by CPU.
    
    Cc: stable@vger.kernel.org
    Tested-by: Boris Brezillon <boris.brezillon@free-electrons.com>
    Reviewed-by: Boris Brezillon <boris.brezillon@free-electrons.com>
    Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>

commit e7e11f99564222d82f0ce84bd521e57d78a6b678
Author: Li Qiang <liq3ea@gmail.com>
Date:   Mon Mar 27 20:10:53 2017 -0700

    drm/vmwgfx: fix integer overflow in vmw_surface_define_ioctl()
    
    In vmw_surface_define_ioctl(), the 'num_sizes' is the sum of the
    'req->mip_levels' array. This array can be assigned any value from
    the user space. As both the 'num_sizes' and the array is uint32_t,
    it is easy to make 'num_sizes' overflow. The later 'mip_levels' is
    used as the loop count. This can lead an oob write. Add the check of
    'req->mip_levels' to avoid this.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Li Qiang <liqiang6-s@360.cn>
    Reviewed-by: Thomas Hellstrom <thellstrom@vmware.com>

commit 53e16798b0864464c5444a204e1bb93ae246c429
Author: Thomas Hellstrom <thellstrom@vmware.com>
Date:   Mon Mar 27 13:06:05 2017 +0200

    drm/vmwgfx: Remove getparam error message
    
    The mesa winsys sometimes uses unimplemented parameter requests to
    check for features. Remove the error message to avoid bloating the
    kernel log.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Thomas Hellstrom <thellstrom@vmware.com>
    Reviewed-by: Brian Paul <brianp@vmware.com>
    Reviewed-by: Sinclair Yeh <syeh@vmware.com>

commit 3ce7803cf3a7bc52c0eb9f516de8b72a0305ad57
Author: Thomas Hellstrom <thellstrom@vmware.com>
Date:   Mon Mar 27 12:38:25 2017 +0200

    drm/ttm: Avoid calling drm_ht_remove from atomic context
    
    On recent kernels, calling drm_ht_remove triggers a might_sleep() warning
    from within vfree(). So avoid calling it from atomic context. The use-cases
    we fix here are both from destructors so there should be no concurrent
    use of the hash tables.
    
    Signed-off-by: Thomas Hellstrom <thellstrom@vmware.com>
    Reviewed-by: Brian Paul <brianp@vmware.com>
    Reviewed-by: Sinclair Yeh <syeh@vmware.com>

commit fe25deb7737ce6c0879ccf79c99fa1221d428bf2
Author: Thomas Hellstrom <thellstrom@vmware.com>
Date:   Mon Mar 27 11:21:25 2017 +0200

    drm/ttm, drm/vmwgfx: Relax permission checking when opening surfaces
    
    Previously, when a surface was opened using a legacy (non prime) handle,
    it was verified to have been created by a client in the same master realm.
    Relax this so that opening is also allowed recursively if the client
    already has the surface open.
    
    This works around a regression in svga mesa where opening of a shared
    surface is used recursively to obtain surface information.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Thomas Hellstrom <thellstrom@vmware.com>
    Reviewed-by: Sinclair Yeh <syeh@vmware.com>

commit 63774069d9527a1aeaa4aa20e929ef5e8e9ecc38
Author: Murray McAllister <murray.mcallister@insomniasec.com>
Date:   Mon Mar 27 11:15:12 2017 +0200

    drm/vmwgfx: avoid calling vzalloc with a 0 size in vmw_get_cap_3d_ioctl()
    
    In vmw_get_cap_3d_ioctl(), a user can supply 0 for a size that is
    used in vzalloc(). This eventually calls dump_stack() (in warn_alloc()),
    which can leak useful addresses to dmesg.
    
    Add check to avoid a size of 0.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Murray McAllister <murray.mcallister@insomniasec.com>
    Reviewed-by: Sinclair Yeh <syeh@vmware.com>

commit 36274ab8c596f1240c606bb514da329add2a1bcd
Author: Murray McAllister <murray.mcallister@insomniasec.com>
Date:   Mon Mar 27 11:12:53 2017 +0200

    drm/vmwgfx: NULL pointer dereference in vmw_surface_define_ioctl()
    
    Before memory allocations vmw_surface_define_ioctl() checks the
    upper-bounds of a user-supplied size, but does not check if the
    supplied size is 0.
    
    Add check to avoid NULL pointer dereferences.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Murray McAllister <murray.mcallister@insomniasec.com>
    Reviewed-by: Sinclair Yeh <syeh@vmware.com>

commit f7652afa8eadb416b23eb57dec6f158529942041
Author: Thomas Hellstrom <thellstrom@vmware.com>
Date:   Mon Mar 27 11:09:08 2017 +0200

    drm/vmwgfx: Type-check lookups of fence objects
    
    A malicious caller could otherwise hand over handles to other objects
    causing all sorts of interesting problems.
    
    Testing done: Ran a Fedora 25 desktop using both Xorg and
    gnome-shell/Wayland.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Thomas Hellstrom <thellstrom@vmware.com>
    Reviewed-by: Sinclair Yeh <syeh@vmware.com>

commit d09c5373e8e4eaaa09233552cbf75dc4c4f21203
Author: Heiko Carstens <heiko.carstens@de.ibm.com>
Date:   Mon Mar 27 09:48:04 2017 +0200

    s390/uaccess: get_user() should zero on failure (again)
    
    Commit fd2d2b191fe7 ("s390: get_user() should zero on failure")
    intended to fix s390's get_user() implementation which did not zero
    the target operand if the read from user space faulted. Unfortunately
    the patch has no effect: the corresponding inline assembly specifies
    that the operand is only written to ("=") and the previous value is
    discarded.
    
    Therefore the compiler is free to and actually does omit the zero
    initialization.
    
    To fix this simply change the contraint modifier to "+", so the
    compiler cannot omit the initialization anymore.
    
    Fixes: c9ca78415ac1 ("s390/uaccess: provide inline variants of get_user/put_user")
    Fixes: fd2d2b191fe7 ("s390: get_user() should zero on failure")
    Cc: stable@vger.kernel.org
    Cc: Al Viro <viro@zeniv.linux.org.uk>
    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit cc66afea58f858ff6da7f79b8a595a67bbb4f9a9
Author: Andi Kleen <ak@linux.intel.com>
Date:   Mon Mar 27 11:32:59 2017 +0200

    x86/mce: Don't print MCEs when mcelog is active
    
    Since:
    
      cd9c57cad3fe ("x86/MCE: Dump MCE to dmesg if no consumers")
    
    all MCEs are printed even when mcelog is running. Fix the regression to
    not print to dmesg when mcelog is running as it is a consumer too.
    
    Signed-off-by: Andi Kleen <ak@linux.intel.com>
    [ Massage commit message. ]
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Tony Luck <tony.luck@intel.com>
    Cc: linux-edac <linux-edac@vger.kernel.org>
    Cc: stable@vger.kernel.org # 4.10..
    Fixes: cd9c57cad3fe ("x86/MCE: Dump MCE to dmesg if no consumers")
    Link: http://lkml.kernel.org/r/20170327093304.10683-2-bp@alien8.de
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

commit ca681ec860d6533b8debda4f6ab2e70e6d519d89
Author: Harald Freudenberger <freude@linux.vnet.ibm.com>
Date:   Wed Mar 15 10:58:07 2017 +0100

    s390/pkey: Fix wrong handling of secure key with old MKVP
    
    When a secure key with an old Master Key Verification
    Pattern was given to the pkey_findcard function, there was
    no responsible card found because only the current MKVP of
    each card was compared. With this fix also the old MKVP
    values are considered and so a matching card able to handle
    the key is reported back to the caller.
    
    Signed-off-by: Harald Freudenberger <freude@linux.vnet.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit 0861b5a754fd5539f527b445aaa61538185c8264
Author: Heiko Carstens <heiko.carstens@de.ibm.com>
Date:   Thu Mar 16 11:02:36 2017 +0100

    s390/smp: fix ipl from cpu with non-zero address
    
    Commit af51160ebd3c ("s390/smp: initialize cpu_present_mask in
    setup_arch") initializes the cpu_present_mask much earlier than
    before. However the cpu detection code relies on the fact that iff
    logical cpu 0 is marked present then also the corresponding physical
    cpu address within the pcpu_devices array slot is valid.
    
    Since commit 44fd22992cb7 ("[PATCH] Register the boot-cpu in the cpu
    maps earlier") this assumption is not true anymore. The patch marks
    logical cpu 0 as present in common code without that architecture code
    had a chance to setup the logical to physical map.
    
    With that change the cpu detection code assumes that the physical cpu
    address of cpu 0 is also 0, which is not necessarily true.
    Subsequently the physical cpu address of the ipl cpu will be mapped to
    a different logical cpu. If that cpu is brought online later the ipl
    cpu will send itself an initial cpu reset sigp signal. This in turn
    completely resets the ipl cpu and the system stops working.
    
    A dump of such a system looks like a "store status" has been
    forgotten. But actually the kernel itself removed all traces which
    would allow to easily tell what went wrong.
    
    To fix this initialize the logical to physical cpu address already in
    smp_setup_processor_id(). In addition remove the initialization of the
    cpu_present_mask and cpu_online_mask for cpu 0, since that has already
    been done. Also add a sanity check, just in case common code will be
    changed again...
    
    The problem can be easily reproduced within a z/VM guest:
    
    > chcpu -d 0
    > vmcp ipl
    
    Fixes: af51160ebd3c ("s390/smp: initialize cpu_present_mask in setup_arch")
    Reported-by: Sebastian Ott <sebott@linux.vnet.ibm.com>
    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit d82c0d12c92705ef468683c9b7a8298dd61ed191
Author: Marcelo Henrique Cerri <marcelo.cerri@canonical.com>
Date:   Mon Mar 13 12:14:58 2017 -0300

    s390/decompressor: fix initrd corruption caused by bss clear
    
    Reorder the operations in decompress_kernel() to ensure initrd is moved
    to a safe location before the bss section is zeroed.
    
    During decompression bss can overlap with the initrd and this can
    corrupt the initrd contents depending on the size of the compressed
    kernel (which affects where the initrd is placed by the bootloader) and
    the size of the bss section of the decompressor.
    
    Also use the correct initrd size when checking for overlaps with
    parmblock.
    
    Fixes: 06c0dd72aea3 ([S390] fix boot failures with compressed kernels)
    Cc: stable@vger.kernel.org
    Reviewed-by: Joy Latten <joy.latten@canonical.com>
    Reviewed-by: Vineetha HariPai <vineetha.hari.pai@canonical.com>
    Signed-off-by: Marcelo Henrique Cerri <marcelo.cerri@canonical.com>
    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>