origin
GIT f89ed2f880ccb117246ba095e12087d9c3df89c5

commit 0894da849f145af51bde88a6b84f95b9c9e0bc66
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Mon Jul 23 14:39:33 2018 -0700

    media: staging: omap4iss: Include asm/cacheflush.h after generic includes
    
    Including asm/cacheflush.h first results in the following build error
    when trying to build sparc32:allmodconfig, because 'struct page' has not
    been declared, and the function declaration ends up creating a separate
    (private) declaration of struct page (as a result of function arguments
    being in the scope of the function declaration and definition, not in
    global scope).
    
    The C scoping rules do not just affect variable visibility, they also
    affect type declaration visibility.
    
    The end result is that when the actual call site is seen in
    <linux/highmem.h>, the 'struct page' type in the caller is not the same
    'struct page' that the function was declared with, resulting in:
    
      In file included from arch/sparc/include/asm/page.h:10:0,
                       ...
                       from drivers/staging/media/omap4iss/iss_video.c:15:
      include/linux/highmem.h: In function 'clear_user_highpage':
      include/linux/highmem.h:137:31: error:
            passing argument 1 of 'sparc_flush_page_to_ram' from incompatible
            pointer type
    
    Include generic includes files first to fix the problem.
    
    Fixes: fc96d58c10162 ("[media] v4l: omap4iss: Add support for OMAP4 camera interface - Video devices")
    Suggested-by: Linus Torvalds <torvalds@linux-foundation.org>
    Acked-by: David S. Miller <davem@davemloft.net>
    Cc: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    [ Added explanation of C scope rules - Linus ]
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit 2fba3573f1cf876ad94992c256c5c410039e60b4
Author: Martin Schwidefsky <schwidefsky@de.ibm.com>
Date:   Tue Jul 24 07:55:18 2018 +0200

    s390: disable gcc plugins
    
    The s390 build currently fails with the latent entropy plugin:
    
    arch/s390/kernel/als.o: In function `verify_facilities':
    als.c:(.init.text+0x24): undefined reference to `latent_entropy'
    als.c:(.init.text+0xae): undefined reference to `latent_entropy'
    make[3]: *** [arch/s390/boot/compressed/vmlinux] Error 1
    make[2]: *** [arch/s390/boot/compressed/vmlinux] Error 2
    make[1]: *** [bzImage] Error 2
    
    This will be fixed with the early boot rework from Vasily, which
    is planned for the 4.19 merge window.
    
    For 4.18 the simplest solution is to disable the gcc plugins and
    reenable them after the early boot rework is upstream.
    
    Reported-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>