mm-mmu_notifier-use-structure-for-invalidate_range_start-end-calls-v2-checkpatch-fixes
Cc: Christian König <christian.koenig@amd.com>

ERROR: code indent should use tabs where possible
#116: FILE: include/linux/mm.h:1506:
+^I^I ^I     struct mmu_notifier_range *range,$

WARNING: please, no space before tabs
#116: FILE: include/linux/mm.h:1506:
+^I^I ^I     struct mmu_notifier_range *range,$

WARNING: function definition argument 'struct mmu_notifier_range *' should also have an identifier name
#131: FILE: include/linux/mmu_notifier.h:223:
+extern int __mmu_notifier_invalidate_range_start(struct mmu_notifier_range *);

ERROR: code indent should use tabs where possible
#951: FILE: mm/memory.c:4111:
+^I^I ^I     struct mmu_notifier_range *range,$

WARNING: please, no space before tabs
#951: FILE: mm/memory.c:4111:
+^I^I ^I     struct mmu_notifier_range *range,$

WARNING: line over 80 characters
#1057: FILE: mm/mmu_notifier.c:183:
+						!range->blockable ? "non-" : "");

WARNING: line over 80 characters
#1191: FILE: mm/oom_kill.c:537:
+			if (mmu_notifier_invalidate_range_start_nonblock(&range)) {

WARNING: line over 80 characters
#1199: FILE: mm/oom_kill.c:542:
+			unmap_page_range(&tlb, vma, range.start, range.end, NULL);

total: 2 errors, 6 warnings, 1132 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-mmu_notifier-use-structure-for-invalidate_range_start-end-calls-v2.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Christian König <christian.koenig@amd.com>
Cc: Dan Williams <dan.j.williams@intel.com>
Cc: Felix Kuehling <felix.kuehling@amd.com>
Cc: Jan Kara <jack@suse.cz>
Cc: Jérôme Glisse <jglisse@redhat.com>
Cc: John Hubbard <jhubbard@nvidia.com>
Cc: Matthew Wilcox <mawilcox@microsoft.com>
Cc: Michal Hocko <mhocko@kernel.org>
Cc: Paolo Bonzini <pbonzini@redhat.com>
Cc: Radim Krcmar <rkrcmar@redhat.com>
Cc: Ralph Campbell <rcampbell@nvidia.com>
Cc: Ross Zwisler <zwisler@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>