origin
GIT 55f058e7574c3615dea4615573a19bdb258696c6

commit 67245ff332064c01b760afa7a384ccda024bfd24
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sat Apr 16 15:16:07 2016 -0700

    devpts: clean up interface to pty drivers
    
    This gets rid of the horrible notion of having that
    
        struct inode *ptmx_inode
    
    be the linchpin of the interface between the pty code and devpts.
    
    By de-emphasizing the ptmx inode, a lot of things actually get cleaner,
    and we will have a much saner way forward.  In particular, this will
    allow us to associate with any particular devpts instance at open-time,
    and not be artificially tied to one particular ptmx inode.
    
    The patch itself is actually fairly straightforward, and apart from some
    locking and return path cleanups it's pretty mechanical:
    
     - the interfaces that devpts exposes all take "struct pts_fs_info *"
       instead of "struct inode *ptmx_inode" now.
    
       NOTE! The "struct pts_fs_info" thing is a completely opaque structure
       as far as the pty driver is concerned: it's still declared entirely
       internally to devpts. So the pty code can't actually access it in any
       way, just pass it as a "cookie" to the devpts code.
    
     - the "look up the pts fs info" is now a single clear operation, that
       also does the reference count increment on the pts superblock.
    
       So "devpts_add/del_ref()" is gone, and replaced by a "lookup and get
       ref" operation (devpts_get_ref(inode)), along with a "put ref" op
       (devpts_put_ref()).
    
     - the pty master "tty->driver_data" field now contains the pts_fs_info,
       not the ptmx inode.
    
     - because we don't care about the ptmx inode any more as some kind of
       base index, the ref counting can now drop the inode games - it just
       gets the ref on the superblock.
    
     - the pts_fs_info now has a back-pointer to the super_block. That's so
       that we can easily look up the information we actually need. Although
       quite often, the pts fs info was actually all we wanted, and not having
       to look it up based on some magical inode makes things more
       straightforward.
    
    In particular, now that "devpts_get_ref(inode)" operation should really
    be the *only* place we need to look up what devpts instance we're
    associated with, and we do it exactly once, at ptmx_open() time.
    
    The other side of this is that one ptmx node could now be associated
    with multiple different devpts instances - you could have a single
    /dev/ptmx node, and then have multiple mount namespaces with their own
    instances of devpts mounted on /dev/pts/.  And that's all perfectly sane
    in a model where we just look up the pts instance at open time.
    
    This will eventually allow us to get rid of our odd single-vs-multiple
    pts instance model, but this patch in itself changes no semantics, only
    an internal binding model.
    
    Cc: Eric Biederman <ebiederm@xmission.com>
    Cc: Peter Anvin <hpa@zytor.com>
    Cc: Andy Lutomirski <luto@amacapital.net>
    Cc: Al Viro <viro@zeniv.linux.org.uk>
    Cc: Peter Hurley <peter@hurleysoftware.com>
    Cc: Serge Hallyn <serge.hallyn@ubuntu.com>
    Cc: Willy Tarreau <w@1wt.eu>
    Cc: Aurelien Jarno <aurelien@aurel32.net>
    Cc: Alan Cox <gnomes@lxorguk.ukuu.org.uk>
    Cc: Jann Horn <jann@thejh.net>
    Cc: Greg KH <greg@kroah.com>
    Cc: Jiri Slaby <jslaby@suse.com>
    Cc: Florian Weimer <fw@deneb.enyo.de>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit 67e658794ca191b3221b143f2a1c10d002c40bc8
Author: Hariprasad Shenai <hariprasad@chelsio.com>
Date:   Fri Apr 15 13:00:18 2016 -0500

    cxgb4: Set VPD size so we can read both VPD structures
    
    Chelsio adapters have two VPD structures stored in the VPD:
    
      - offset 0x000: an abbreviated VPD, and
      - offset 0x400: the complete VPD.
    
    After 104daa71b396 ("PCI: Determine actual VPD size on first access"), the
    PCI core computes the valid VPD size by parsing the VPD starting at offset
    0x0.  That size only includes the abbreviated VPD structure, so reads of
    the complete VPD at 0x400 fail.
    
    Explicitly set the VPD size with pci_set_vpd_size() so the driver can read
    both VPD structures.
    
    [bhelgaas: changelog, split patches, rename to pci_set_vpd_size() and
    return int (not ssize_t)]
    Fixes: 104daa71b396 ("PCI: Determine actual VPD size on first access")
    Tested-by: Steve Wise <swise@opengridcomputing.com>
    Signed-off-by: Casey Leedom <leedom@chelsio.com>
    Signed-off-by: Hariprasad Shenai <hariprasad@chelsio.com>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

commit cb92148b58a49455f3a7204eba3aee09a8b7683c
Author: Hariprasad Shenai <hariprasad@chelsio.com>
Date:   Fri Apr 15 13:00:11 2016 -0500

    PCI: Add pci_set_vpd_size() to set VPD size
    
    After 104daa71b396 ("PCI: Determine actual VPD size on first access"), the
    PCI core computes the valid VPD size by parsing the VPD starting at offset
    0x0.  We don't attempt to read past that valid size because that causes
    some devices to crash.
    
    However, some devices do have data past that valid size.  For example,
    Chelsio adapters contain two VPD structures, and the driver needs both of
    them.
    
    Add pci_set_vpd_size().  If a driver knows it is safe to read past the end
    of the VPD data structure at offset 0, it can use pci_set_vpd_size() to
    allow access to as much data as it needs.
    
    [bhelgaas: changelog, split patches, rename to pci_set_vpd_size() and
    return int (not ssize_t)]
    Fixes: 104daa71b396 ("PCI: Determine actual VPD size on first access")
    Tested-by: Steve Wise <swise@opengridcomputing.com>
    Signed-off-by: Casey Leedom <leedom@chelsio.com>
    Signed-off-by: Hariprasad Shenai <hariprasad@chelsio.com>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

commit 2fd92273646abad21766ddfbfa00b6f927362308
Author: Heiko Carstens <heiko.carstens@de.ibm.com>
Date:   Thu Apr 14 09:00:27 2016 +0200

    s390: add CPU_BIG_ENDIAN config option
    
    Make sure that s390 appears to be a big endian machine by defining
    this config option.
    
    Without this s390 appears to be little endian as seen by e.g. the
    recordmount script: "perl ./scripts/recordmcount.pl "s390" "little"
    "64""
    This has no practical impact within the script since the endian
    variable is only evaluated for mips. However there are already a
    couple of common code places which evaluate this config option. None
    of them is relevant for s390 currently though.
    
    To avoid any issues in the future (and fix the recordmcount oddity)
    add the new config option.
    
    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit 8497695243f70fd19ed6cf28b63584f1b608b5f9
Author: Heiko Carstens <heiko.carstens@de.ibm.com>
Date:   Wed Apr 13 11:05:20 2016 +0200

    s390/spinlock: avoid yield to non existent cpu
    
    arch_spin_lock_wait_flags() checks if a spinlock is not held before
    trying a compare and swap instruction. If the lock is unlocked it
    tries the compare and swap instruction, however if a different cpu
    grabbed the lock in the meantime the instruction will fail as
    expected.
    
    Subsequently the arch_spin_lock_wait_flags() incorrectly tries to
    figure out if the cpu that holds the lock is running. However it is
    using the wrong cpu number for this (-1) and then will also yield the
    current cpu to the wrong cpu.
    
    Fix this by adding a missing continue statement.
    
    Fixes: 470ada6b1a1d ("s390/spinlock: refactor arch_spin_lock_wait[_flags]")
    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Acked-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit 1378a683443753923eb22d01ce322e92a383ba8a
Author: Gerald Schaefer <gerald.schaefer@de.ibm.com>
Date:   Fri Apr 8 13:23:52 2016 +0200

    s390/dcssblk: fix possible deadlock in remove vs. per-device attributes
    
    dcssblk_remove_store() holds the dcssblk_devices_sem semaphore while
    calling device_unregister(), which in turn tries to acquire the kernfs
    kn->dev_map rwsem for the device sysfs subtree. The same rwsem is also
    acquired when using the per-device sysfs attributes in the device sub-tree,
    and the attribute handlers then also acquire the dcssblk_devices_sem.
    
    This can lead to a deadlock when removing a DCSS while concurrently
    reading from / writing to one of its sysfs attributes. The following
    lockdep warning hinted towards the issue (CPU0 = dcssblk_remove_store,
    CPU1 = dcssblk_shared_store):
    
    [   76.496047]  Possible unsafe locking scenario:
    
    [   76.496054]        CPU0                    CPU1
    [   76.496059]        ----                    ----
    [   76.496087]   lock(&dcssblk_devices_sem);
    [   76.496090]                                lock(s_active#175);
    [   76.496106]                                lock(&dcssblk_devices_sem);
    [   76.496110]   lock(s_active#175);
    [   76.496115]
     *** DEADLOCK ***
    
    Fix this by releasing the dcssblk_devices_sem semaphore, which only
    protects internal DCSS data, before calling device_unregister().
    
    Signed-off-by: Gerald Schaefer <gerald.schaefer@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit f709b45ec461b548c41a00044dba1f1b572783bf
Author: Tom Lendacky <thomas.lendacky@amd.com>
Date:   Wed Apr 13 10:52:25 2016 -0500

    crypto: ccp - Prevent information leakage on export
    
    Prevent information from leaking to userspace by doing a memset to 0 of
    the export state structure before setting the structure values and copying
    it. This prevents un-initialized padding areas from being copied into the
    export area.
    
    Cc: <stable@vger.kernel.org> # 3.14.x-
    Reported-by: Ben Hutchings <ben@decadent.org.uk>
    Signed-off-by: Tom Lendacky <thomas.lendacky@amd.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit 0851561d9c965df086ef8a53f981f5f95a57c2c8
Author: Xiaodong Liu <xiaodong.liu@intel.com>
Date:   Tue Apr 12 09:45:51 2016 +0000

    crypto: sha1-mb - use corrcet pointer while completing jobs
    
    In sha_complete_job, incorrect mcryptd_hash_request_ctx pointer is used
    when check and complete other jobs. If the memory of first completed req
    is freed, while still completing other jobs in the func, kernel will
    crash since NULL pointer is assigned to RIP.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Xiaodong Liu <xiaodong.liu@intel.com>
    Acked-by: Tim Chen <tim.c.chen@linux.intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit 6f0904ada402a45b3a0a3b9b6507d91d3a9da67a
Author: Tadeusz Struk <tadeusz.struk@intel.com>
Date:   Wed Apr 6 14:42:32 2016 -0700

    crypto: rsa-pkcs1pad - fix dst len
    
    The output buffer length has to be at least as big as the key_size.
    It is then updated to the actual output size by the implementation.
    
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit b2d7a9cd3ff8ec561348267c2ef7d47b2b91e801
Author: Fabio Estevam <fabio.estevam@nxp.com>
Date:   Mon Mar 28 18:45:36 2016 -0300

    Revert "PCI: imx6: Add support for active-low reset GPIO"
    
    Commit 5c5fb40de8f1 ("PCI: imx6: Add support for active-low reset GPIO")
    cause regressions on some boards like MX6 Gateworks Ventana, for example.
    
    The reason for the breakage is that this commit sets the GPIO polarity in
    the wrong logic level.
    
    Also, the commit log is wrong because active-low reset GPIO is what the
    driver used to support since the beginning.
    
    So keep the old behavior that ignores the GPIO polarity specified in the
    device tree and treat the PCI reset GPIO as active-low.
    
    Reported-by: Krzysztof Hałasa <khalasa@piap.pl>
    Tested-by: Tim Harvey <tharvey@gateworks.com>	# Gateworks Ventana
    Signed-off-by: Fabio Estevam <fabio.estevam@nxp.com>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
    Acked-by: Tim Harvey <tharvey@gateworks.com>
    Acked-by: Lucas Stach <l.stach@pengutronix.de>
    CC: stable@vger.kernel.org	# v4.5+

commit 4f375903ccbff78e1da02133e51e37a097cd3313
Author: Sudip Mukherjee <sudipm.mukherjee@gmail.com>
Date:   Fri Apr 1 13:35:16 2016 +0100

    s390/seccomp: include generic seccomp header file
    
    Fixes this build error on linux-next:
    
    kernel/seccomp.c: In function '__secure_computing_strict':
    kernel/seccomp.c:526:3: error: implicit declaration of function
    				'get_compat_mode1_syscalls'
    
    The retrieval of compat syscall numbers were moved into inline function
    defined in asm-generic header but the asm-generic header is not being
    used by s390.
    
    [heiko.carstens@de.ibm.com]: even though the build error will trigger
    only in the next merge window it makes sense to include the generic
    header file already now.
    
    Fixes: ("seccomp: Get compat syscalls from asm-generic header")
    Cc: Matt Redfearn <matt.redfearn@imgtec.com>
    Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>
    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit 9d89d9e61d361f3adb75e1aebe4bb367faf16cfa
Author: Sebastian Ott <sebott@linux.vnet.ibm.com>
Date:   Thu Mar 31 11:48:31 2016 +0200

    s390/pci: add extra padding to function measurement block
    
    Newer machines might use a different (larger) format for function
    measurement blocks. To ensure that we comply with the alignment
    requirement on these machines and prevent memory corruption (when
    firmware writes more data than we expect) add 16 padding bytes
    at the end of the fmb.
    
    Cc: stable@vger.kernel.org # v4.1+
    Signed-off-by: Sebastian Ott <sebott@linux.vnet.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

commit b707c65ae70e24c47a0ce4a7279224ce8f0ffb7f
Author: Sebastian Ott <sebott@linux.vnet.ibm.com>
Date:   Tue Mar 22 19:00:55 2016 +0100

    s390/scm_blk: fix deadlock for requests != REQ_TYPE_FS
    
    When we refuse a non REQ_TYPE_FS request in the build request function
    we already hold the queue lock. Thus we must not call blk_end_request_all
    but __blk_end_request_all.
    
    Reported-by: Peter Oberparleiter <oberpar@linux.vnet.ibm.com>
    Fixes: de9587a ('s390/scm_blk: fix endless loop for requests != REQ_TYPE_FS')
    Signed-off-by: Sebastian Ott <sebott@linux.vnet.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>