kernel-padata-hide-unused-functions-checkpatch-fixes
ERROR: spaces required around that '=' (ctx:WxO)
#48: FILE: kernel/padata.c:689:
+		err =-EINVAL;
 		    ^

ERROR: space required before that '-' (ctx:OxV)
#48: FILE: kernel/padata.c:689:
+		err =-EINVAL;
 		     ^

total: 2 errors, 0 warnings, 86 lines checked

./patches/kernel-padata-hide-unused-functions.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>