mm-factor-commit-limit-calculation-fix-fix
Fix compilation error reported by Fengguang:
tree:   git://git.kernel.org/pub/scm/linux/kernel/git/mhocko/mm.git since-3.12
head:   e07b643d945e4802be41685a21065c703611052b
commit: e07b643d945e4802be41685a21065c703611052b [76/76] Revert "mm-factor-commit-limit-calculation-fix"
config: make ARCH=powerpc allnoconfig

All error/warnings:

   In file included from arch/powerpc/kernel/syscalls.c:32:0:
>> include/linux/mman.h:97:100: error: function declaration isn't a prototype [-Werror=strict-prototypes]
    static inline unsigned long vm_commit_limit()
                                                                                                       ^
   cc1: all warnings being treated as errors

vim +97 include/linux/mman.h

    91                 _calc_vm_trans(flags, MAP_LOCKED,     VM_LOCKED    );
    92  }
    93
    94  /*
    95   * Commited memory limit enforced when OVERCOMMIT_NEVER policy is used
    96   */
  > 97  static inline unsigned long vm_commit_limit()
    98  {
    99          return ((totalram_pages - hugetlb_total_pages())
   100                  * sysctl_overcommit_ratio / 100) + total_swap_pages;

This has been originally fixed by mm-factor-commit-limit-calculation-fix
which got reverted due to other issue.

Signed-off-by: Michal Hocko <mhocko@suse.cz>