printk-add-kernel-parameter-to-control-writes-to-dev-kmsg-checkpatch-fixes
ERROR: else should follow close brace '}'
#160: FILE: kernel/printk/printk.c:120:
+	}
+	else

WARNING: line over 80 characters
#263: FILE: kernel/printk/printk.c:745:
+	if ((system_state != SYSTEM_BOOTING) && !(devkmsg_log & DEVKMSG_LOG_MASK_ON)) {

total: 1 errors, 1 warnings, 250 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/printk-add-kernel-parameter-to-control-writes-to-dev-kmsg.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Borislav Petkov <bp@suse.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>