mm-mmu_gather-remove-__tlb_reset_range-for-force-flush-checkpatch-fixes
WARNING: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#32: 
		map_address = mmap(distant_area, (size_t) map_size, PROT_WRITE | PROT_READ,

ERROR: trailing whitespace
#157: FILE: mm/mmu_gather.c:266:
+^I^I */ $

total: 1 errors, 1 warnings, 33 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-mmu_gather-remove-__tlb_reset_range-for-force-flush.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Yang Shi <yang.shi@linux.alibaba.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>