hugetlb: fix ARM 3level page tables
The check for __HAVE_ARCH_HUGE_PTEP_GET comes before the definition,
leading to an extraneous definition of huge_ptep_get:

In file included from arch/arm/include/asm/hugetlb.h:28,
                 from include/linux/hugetlb.h:456,
                 from arch/arm/kvm/../../../virt/kvm/arm/mmu.c:22:
arch/arm/include/asm/hugetlb-3level.h:33:21: error: redefinition of 'huge_ptep_get'
 static inline pte_t huge_ptep_get(pte_t *ptep)

Change the header file inclusions to be in the correct order for
this to work.

Link: http://lkml.kernel.org/r/20181005161722.904274-1-arnd@arndb.de
Fixes: bb1d18ffc7ae ("hugetlb: introduce generic version of huge_ptep_get")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Alexandre Ghiti <alex@ghiti.fr>
Cc: Luiz Capitulino <lcapitulino@redhat.com>
Cc: Mike Kravetz <mike.kravetz@oracle.com>
Cc: Helge Deller <deller@gmx.de>
Cc: Catalin Marinas <catalin.marinas@arm.com>
Cc: Paul Burton <paul.burton@mips.com>
Cc: Ingo Molnar <mingo@kernel.org>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>