x86-add-support-for-pud-sized-transparent-hugepages-checkpatch-fixes
ERROR: space prohibited before that ',' (ctx:WxW)
#201: FILE: arch/x86/include/asm/pgtable.h:820:
+				     pud_t *pudp , pud_t pud)
 				                 ^

WARNING: line over 80 characters
#230: FILE: arch/x86/include/asm/pgtable.h:932:
+static inline pud_t pudp_huge_get_and_clear(struct mm_struct *mm, unsigned long addr,

WARNING: Block comments use * on subsequent lines
#263: FILE: arch/x86/include/asm/pgtable_64.h:115:
+	/* native_local_pudp_get_and_clear,
+	   but duplicated because of cyclic dependency */

WARNING: Block comments use a trailing */ on a separate line
#263: FILE: arch/x86/include/asm/pgtable_64.h:115:
+	   but duplicated because of cyclic dependency */

WARNING: Missing a blank line after declarations
#265: FILE: arch/x86/include/asm/pgtable_64.h:117:
+	pud_t ret = *pudp;
+	native_pud_clear(pudp);

total: 1 errors, 4 warnings, 265 lines checked

./patches/x86-add-support-for-pud-sized-transparent-hugepages.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: "H. Peter Anvin" <hpa@zytor.com>
Cc: Ingo Molnar <mingo@elte.hu>
Cc: Matthew Wilcox <willy@linux.intel.com>
Cc: Thomas Gleixner <tglx@linutronix.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>