mm-unexport-__get_user_pages_unlocked-checkpatch-fixes
ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 0123456789ab ("commit description")'
#16: 
flag.  However, this flag was originally silently dropped by 1e9877902dc7e

WARNING: line over 80 characters
#89: FILE: mm/nommu.c:179:
+static long __get_user_pages_unlocked(struct task_struct *tsk, struct mm_struct *mm,

WARNING: line over 80 characters
#90: FILE: mm/nommu.c:180:
+				      unsigned long start, unsigned long nr_pages,

WARNING: line over 80 characters
#91: FILE: mm/nommu.c:181:
+			              struct page **pages, unsigned int gup_flags)

ERROR: code indent should use tabs where possible
#91: FILE: mm/nommu.c:181:
+^I^I^I              struct page **pages, unsigned int gup_flags)$

total: 2 errors, 3 warnings, 116 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-unexport-__get_user_pages_unlocked.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Lorenzo Stoakes <lstoakes@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>