memcg-simplify-and-inline-__mem_cgroup_from_kmem-fix.patch
virt_to_head_page() is defined in <linux/mm.h> but you don't include it,
and the commit breaks build for me (on v4.3-rc5-mmotm-2015-10-15-15-20).

  CC      arch/x86/kernel/asm-offsets.s
In file included from /home/kas/linux/mm/include/linux/swap.h:8:0,
                 from /home/kas/linux/mm/include/linux/suspend.h:4,
                 from /home/kas/linux/mm/arch/x86/kernel/asm-offsets.c:12:
/home/kas/linux/mm/include/linux/memcontrol.h: In function ‘mem_cgroup_from_kmem’:
/home/kas/linux/mm/include/linux/memcontrol.h:841:9: error: implicit declaration of function ‘virt_to_head_page’ [-Werror=implicit-function-declaration]
  page = virt_to_head_page(ptr);
         ^
/home/kas/linux/mm/include/linux/memcontrol.h:841:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  page = virt_to_head_page(ptr);
       ^
In file included from /home/kas/linux/mm/include/linux/suspend.h:8:0,
                 from /home/kas/linux/mm/arch/x86/kernel/asm-offsets.c:12:
/home/kas/linux/mm/include/linux/mm.h: At top level:
/home/kas/linux/mm/include/linux/mm.h:452:28: error: conflicting types for ‘virt_to_head_page’
 static inline struct page *virt_to_head_page(const void *x)
                            ^
In file included from /home/kas/linux/mm/include/linux/swap.h:8:0,
                 from /home/kas/linux/mm/include/linux/suspend.h:4,
                 from /home/kas/linux/mm/arch/x86/kernel/asm-offsets.c:12:
/home/kas/linux/mm/include/linux/memcontrol.h:841:9: note: previous implicit declaration of ‘virt_to_head_page’ was here
  page = virt_to_head_page(ptr);
         ^
cc1: some warnings being treated as errors

The patch below fixes it for me (and for allmodconfig on x86-64), but I'm not
sure if it have any side effects on other configurations.