mm-hmm-struct-hmm-is-only-use-by-hmm-mirror-functionality-v2-fix
Compiler is complaining for allnoconfig

kernel/fork.c: In function 'mm_init':
kernel/fork.c:814:2: error: implicit declaration of function 'hmm_mm_init' [-Werror=implicit-function-declaration]
  hmm_mm_init(mm);
  ^
kernel/fork.c: In function '__mmdrop':
kernel/fork.c:893:2: error: implicit declaration of function 'hmm_mm_destroy' [-Werror=implicit-function-declaration]
  hmm_mm_destroy(mm);

Make sure that hmm_mm_init/hmm_mm_destroy empty stups are defined when
CONFIG_HMM is disabled.

Signed-off-by: Michal Hocko <mhocko@suse.com>