hfs-hfsplus-follow-macos-time-behavior-checkpatch-fixes
ERROR: space prohibited after that '-' (ctx:WxW)
#87: FILE: fs/hfs/hfs_fs.h:265:
+	ut -= - sys_tz.tz_minuteswest * 60;
 	      ^

WARNING: line over 80 characters
#100: FILE: fs/hfs/hfs_fs.h:276:
+#define hfs_m_to_utime(time)   (struct timespec){ .tv_sec = __hfs_m_to_utime(time) }

total: 1 errors, 1 warnings, 71 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/hfs-hfsplus-follow-macos-time-behavior.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>