autofs: make autofs4 and autofs mutually exclusive
The autofs4 implementation is just a redirect to autofs now, but that
also means we can't have both built into the same kernel:

fs/autofs/inode.o: In function `autofs_new_ino':
inode.c:(.text+0x1b8): multiple definition of `autofs_new_ino'
fs/autofs/inode.o:inode.c:(.text+0x1b8): first defined here
fs/autofs/inode.o: In function `autofs_clean_ino':
inode.c:(.text+0x288): multiple definition of `autofs_clean_ino'

There is also a problem with trying to build both in parallel, which
leads to two 'make' processes writing to the same fs/autofs/.*.o.cmd
file, causing corruption that manifests like

fs/autofs4/../autofs/.expire.o.cmd:679: *** missing separator.  Stop.

Making AUTOFS4_FS depend on AUTOFS_FS being disabled should avoid all
configurations that run into either issue.

Link: http://lkml.kernel.org/r/20180529094702.4092022-1-arnd@arndb.de
Fixes: mmotm ("autofs: update fs/autofs4/Makefile")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Ian Kent <raven@themaw.net>
Cc: Mark Brown <broonie@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>