tools-modifying-page-types-to-include-shared-map-counts-checkpatch-fixes
ERROR: spaces required around that ':' (ctx:VxE)
#51: FILE: tools/vm/page-types.c:308:
+	return kpagecount_fd < 0 ? pages:
 	                                ^

total: 1 errors, 0 warnings, 228 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/tools-modifying-page-types-to-include-shared-map-counts.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Christian Hansen <chansen3@cisco.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>