mm-maintain-randomization-of-page-free-lists-checkpatch-fixes
ERROR: code indent should use tabs where possible
#125: FILE: mm/shuffle.h:43:
+                return false;$

WARNING: please, no spaces at the start of a line
#125: FILE: mm/shuffle.h:43:
+                return false;$

total: 1 errors, 1 warnings, 96 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-maintain-randomization-of-page-free-lists.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>