Fix misapplied "mm: mlock: add new mlock system call"
__NR_syscalls wasn't updated properly which has been caught by 0-day
compile test:
>> include/uapi/asm-generic/unistd.h:713:1: error: array index in initializer exceeds array bounds
   include/uapi/asm-generic/unistd.h:713:1: error: (near initialization for 'sys_call_table')

vim +713 include/uapi/asm-generic/unistd.h

   707  __SYSCALL(__NR_memfd_create, sys_memfd_create)
   708  #define __NR_bpf 280
   709  __SYSCALL(__NR_bpf, sys_bpf)
   710  #define __NR_execveat 281
   711  __SC_COMP(__NR_execveat, sys_execveat, compat_sys_execveat)
   712  #define __NR_mlock2 283
 > 713  __SYSCALL(__NR_mlock2, sys_mlock2)
   714
   715  #undef __NR_syscalls
   716  #define __NR_syscalls 283

The original patch was correct.

Signed-off-by: Michal Hocko <mhocko@suse.com>