ipc-sem-optimize-perform_atomic_semop-checkpatch-fixes
WARNING: Missing a blank line after declarations
#132: FILE: ipc/sem.c:747:
+			int undo = un->semadj[sop->sem_num] - sem_op;
+			un->semadj[sop->sem_num] = undo;

ERROR: spaces required around that '?' (ctx:VxW)
#142: FILE: ipc/sem.c:757:
+	return sop->sem_flg & IPC_NOWAIT? -EAGAIN : 1;
 	                                ^

total: 1 errors, 1 warnings, 171 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/ipc-sem-optimize-perform_atomic_semop.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Davidlohr Bueso <dave@stgolabs.net>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>