powerpc-add-support-for-loading-elf-kernels-with-kexec_file_load-fix
This patch causes a warning in GCC 4.6.3:

arch/powerpc/kernel/kexec_elf_64.c:211:6: error: 'initrd_load_addr' may be used uninitialized in this function [-Werror=uninitialized]
cc1: all warnings being treated as errors
make[2]: *** [arch/powerpc/kernel/kexec_elf_64.o] Error 1
make[1]: *** [arch/powerpc/kernel] Error 2
make: *** [sub-make] Error 2

Link: http://lkml.kernel.org/r/1931074.eWqeHQFLY5@hactar
Signed-off-by: Thiago Jung Bauermann <bauerman@linux.vnet.ibm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>