mm: pagewalk: fix unused variable warning
One of the pagewalk patches introduced a harmless warning:

mm/hmm.c: In function 'hmm_vma_walk_pud':
mm/hmm.c:478:9: error: unused variable 'pmdp' [-Werror=3Dunused-variable]
  pmd_t *pmdp;
         ^~~~
mm/hmm.c:477:30: error: unused variable 'next' [-Werror=3Dunused-variable=
]
  unsigned long addr =3D start, next;
                              ^~~~

Remove both of the now-unused variables.

Link: http://lkml.kernel.org/r/20200107204607.1533842-1-arnd@arndb.de
Fixes: cb4d03d5fb4c ("mm: pagewalk: add p4d_entry() and pgd_entry()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: John Hubbard <jhubbard@nvidia.com>
Reviewed-by: Steven Price <steven.price@arm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>