drivers/leds/leds-lp3952.c: work around gcc-4.4.4 union initializer bug
drivers/leds/leds-lp3952.c: In function 'lp3952_set_pattern_gen_cmd':
drivers/leds/leds-lp3952.c:156: error: unknown field 'r' specified in initializer
drivers/leds/leds-lp3952.c:156: warning: missing braces around initializer
drivers/leds/leds-lp3952.c:156: warning: (near initialization for 'line.<anonymous>')
drivers/leds/leds-lp3952.c:157: error: unknown field 'g' specified in initializer
drivers/leds/leds-lp3952.c:157: warning: excess elements in struct initializer
drivers/leds/leds-lp3952.c:157: warning: (near initialization for 'line')
drivers/leds/leds-lp3952.c:158: error: unknown field 'b' specified in initializer
drivers/leds/leds-lp3952.c:158: warning: excess elements in struct initializer
drivers/leds/leds-lp3952.c:158: warning: (near initialization for 'line')
drivers/leds/leds-lp3952.c:159: error: unknown field 'cet' specified in initializer
drivers/leds/leds-lp3952.c:159: warning: excess elements in struct initializer
drivers/leds/leds-lp3952.c:159: warning: (near initialization for 'line')
drivers/leds/leds-lp3952.c:160: error: unknown field 'tt' specified in initializer
drivers/leds/leds-lp3952.c:161: warning: excess elements in struct initializer
drivers/leds/leds-lp3952.c:161: warning: (near initialization for 'line')

Fixes: 1574a45ad7467d6a8c6 ("leds: LED driver for TI LP3952 6-Channel Color LED")
Cc: Tony Makkiel <tony.makkiel@daqri.com>
Cc: Mika Westerberg <mika.westerberg@linux.intel.com>
Cc: Jacek Anaszewski <j.anaszewski@samsung.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>