Revert "mm-factor-commit-limit-calculation-fix"
This reverts commit 2f11d7af8df66cb4f217b6293ad8189aa101d601.

because it break NOMMU configuration as reported by Fengguang:

tree:   git://git.kernel.org/pub/scm/linux/kernel/git/mhocko/mm.git since-3.12
head:   2f11d7af8df66cb4f217b6293ad8189aa101d601
commit: 2f11d7af8df66cb4f217b6293ad8189aa101d601 [75/75] mm-factor-commit-limit-calculation-fix
config: make ARCH=blackfin BF526-EZBRD_defconfig

All error/warnings:

   mm/built-in.o: In function `__vm_enough_memory':
   (.text+0x11b4c): undefined reference to `vm_commit_limit'
   fs/built-in.o: In function `meminfo_proc_show':
>> fs/proc/meminfo.c:(.text+0x37ef0): undefined reference to `vm_commit_limit'

Signed-off-by: Michal Hocko <mhocko@suse.cz>