revert-mm-mempool-only-set-__gfp_nomemalloc-if-there-are-free-elements-checkpatch-fixes
ERROR: "foo * bar" should be "foo *bar"
#90: FILE: mm/mempool.c:311:
+void * mempool_alloc(mempool_t *pool, gfp_t gfp_mask)

total: 5 errors, 0 warnings, 52 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/revert-mm-mempool-only-set-__gfp_nomemalloc-if-there-are-free-elements.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Michal Hocko <mhocko@suse.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>