mm-oom-remove-prefer-children-over-parent-heuristic-checkpatch-fixes
ERROR: "(foo*)" should be "(foo *)"
#167: FILE: mm/oom_kill.c:985:
+				      (void*) message);

total: 1 errors, 0 warnings, 128 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mm-oom-remove-prefer-children-over-parent-heuristic.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Shakeel Butt <shakeelb@google.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>