powerpc/mm: Fix build error
On powerpc, we need to explicitly include percpu.h in mmzone.h to avoid the
following build error:

In file included from /home/laurent/linux/include/linux/gfp.h:6:0,
                 from /home/laurent/linux/include/linux/umh.h:4,
                 from /home/laurent/linux/include/linux/kmod.h:22,
                 from /home/laurent/linux/include/linux/module.h:13,
                 from /home/laurent/linux/init/main.c:16:
/home/laurent/linux/include/linux/mmzone.h: In function
‘update_reclaim_stat_scanned’:
/home/laurent/linux/include/linux/mmzone.h:280:7: error: implicit
declaration of function ‘this_cpu_ptr’
[-Werror=implicit-function-declaration]
       this_cpu_ptr(lruvec->reclaim_stat_cpu);
       ^
/home/laurent/linux/include/linux/mmzone.h:280:7: warning: initialization
makes pointer from integer without a cast [enabled by default]
/home/laurent/linux/include/linux/mmzone.h: In function
‘update_reclaim_stat_rotated’:
/home/laurent/linux/include/linux/mmzone.h:290:7: warning: initialization
makes pointer from integer without a cast [enabled by default]
       this_cpu_ptr(lruvec->reclaim_stat_cpu);
       ^
cc1: some warnings being treated as errors
/home/laurent/linux/scripts/Makefile.build:312: recipe for target
'init/main.o' failed
make[3]: *** [init/main.o] Error 1

Signed-off-by: Laurent Dufour <ldufour@linux.vnet.ibm.com>