origin
GIT 02214bfc89c71bcc5167f653994cfa5c57f10ff1

commit 324493fba77500592bbaa66421729421f139d4b5
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Tue Aug 14 12:02:31 2018 -0400

    media: platform: fix cros-ec-cec build error
    
    Fix build when MFD_CROS_EC is not enabled but COMPILE_TEST=y.
    Fixes this build error:
    
    ERROR: "cros_ec_cmd_xfer_status" [drivers/media/platform/cros-ec-cec/cros-ec-cec.ko] undefined!
    
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Neil Armstrong <narmstrong@baylibre.com>
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>

commit dab99a0f77e9764a00b0203d0155ca134247f461
Author: Hans Verkuil <hverkuil@xs4all.nl>
Date:   Thu Aug 30 06:18:22 2018 -0400

    media: staging/media/mt9t031/Kconfig: remove bogus entry
    
    The 'config SOC_CAMERA_IMX074' is a copy-and-paste error and should be removed.
    This Kconfig is for mt9t031 only.
    
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>

commit 9d2ac5f4bec00a0697ab77c999ef38753b3cb900
Author: Jacopo Mondi <jacopo+renesas@jmondi.org>
Date:   Fri Aug 3 12:40:58 2018 +0200

    media: i2c: mt9v111: Fix v4l2-ctrl error handling
    
    Fix error handling of v4l2_ctrl creation by inspecting the ctrl.error flag
    instead of testing for each returned value correctness.
    
    As reported by Dan Carpenter returning PTR_ERR() on the v4l2_ctrl_new_std()
    return value is also wrong, as that function return NULL on error.
    
    While at there re-order the cleanup path to respect the operation inverse
    order.
    
    Fixes: aab7ed1c "media: i2c: Add driver for Aptina MT9V111"
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Jacopo Mondi <jacopo+renesas@jmondi.org>
    Signed-off-by: Sakari Ailus <sakari.ailus@linux.intel.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@kernel.org>

commit 3799eca51c5be3cd76047a582ac52087373b54b3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Aug 15 06:27:28 2018 -0400

    media: camss: add missing includes
    
    Multiple files in this driver fail to build because of missing
    header inclusions:
    
    drivers/media/platform/qcom/camss/camss-csiphy-2ph-1-0.c: In function 'csiphy_hw_version_read':
    drivers/media/platform/qcom/camss/camss-csiphy-2ph-1-0.c:31:18: error: implicit declaration of function 'readl_relaxed'; did you mean 'xchg_relaxed'? [-Werror=implicit-function-declaration]
    drivers/media/platform/qcom/camss/camss-csiphy-3ph-1-0.c: In function 'csiphy_hw_version_read':
    drivers/media/platform/qcom/camss/camss-csiphy-3ph-1-0.c:52:2: error: implicit declaration of function 'writel' [-Werror=implicit-function-declaration]
    
    Add linux/io.h there and in all other files that call
    readl/writel and related interfaces.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Todor Tomov <todor.tomov@linaro.org>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>

commit 55b518998996cc935d294bbf1f07ddba58b8b89e
Author: Todor Tomov <todor.tomov@linaro.org>
Date:   Tue Aug 14 11:57:35 2018 -0400

    media: camss: Use managed memory allocations
    
    Use managed memory allocations for structs which are used until
    the driver is removed.
    
    Signed-off-by: Todor Tomov <todor.tomov@linaro.org>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>

commit 44a9ffd4eb99ada6c1496a735a414414fef30696
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Aug 17 05:53:42 2018 -0400

    media: camss: mark PM functions as __maybe_unused
    
    The empty suspend/resume functions cause a build warning
    when they are unused:
    
    drivers/media/platform/qcom/camss/camss.c:1001:12: error: 'camss_runtime_resume' defined but not used [-Werror=unused-function]
    drivers/media/platform/qcom/camss/camss.c:996:12: error: 'camss_runtime_suspend' defined but not used [-Werror=unused-function]
    
    Mark them as __maybe_unused so the compiler can silently drop them.
    
    Fixes: 02afa816dbbf ("media: camss: Add basic runtime PM support")
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Todor Tomov <todor.tomov@linaro.org>
    Acked-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>

commit 312f73b648626a0526a3aceebb0a3192aaba05ce
Author: Jozef Balga <jozef.balga@gmail.com>
Date:   Tue Aug 21 05:01:04 2018 -0400

    media: af9035: prevent buffer overflow on write
    
    When less than 3 bytes are written to the device, memcpy is called with
    negative array size which leads to buffer overflow and kernel panic. This
    patch adds a condition and returns -EOPNOTSUPP instead.
    Fixes bugzilla issue 64871
    
    [mchehab+samsung@kernel.org: fix a merge conflict and changed the
     condition to match the patch's comment, e. g. len == 3 could
     also be valid]
    Signed-off-by: Jozef Balga <jozef.balga@gmail.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>

commit 4fbf51ee6e822ac28be28ff25883745131e8c4a3
Author: Hans Verkuil <hverkuil@xs4all.nl>
Date:   Thu Aug 23 09:55:43 2018 -0400

    media: video_function_calls.rst: drop obsolete video-set-attributes reference
    
    This fixes this warning:
    
    Documentation/media/uapi/dvb/video_function_calls.rst:9: WARNING: toctree contains
    reference to nonexisting document 'uapi/dvb/video-set-attributes'
    
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>