arch/powerpc/kernel/module_64.c:463: undefined reference to `.elf64_apply_relocate_add'
Am Samstag, 15. Oktober 2016, 23:14:20 BRST schrieb kbuild test robot:
>    arch/powerpc/kernel/built-in.o: In function `apply_relocate_add':
> >> arch/powerpc/kernel/module_64.c:463: undefined reference to
> >> `.elf64_apply_relocate_add'

This is because my kexec_file_load patches lost a few hunks.
The patch below fixes the issue.

Many of the problems with this patch series stem from the fact that it
conflicted with the s/CONFIG_WORD_SIZE/BITS/ change that went into v4.9-rc1.
I will post a new version rebased on top of v4.9-rc1, this should get things
back on track. I'll have them ready by tomorrow.

Thank you for your patience.

index 3bf8dc6ccf7d..6ff8927a8a05 100644
Link: http://lkml.kernel.org/r/1526295.DW58yBHL0y@morokweng

Signed-off-by: Andrew Morton <akpm@linux-foundation.org>