mm-meminit-inline-some-helper-functions-fix2.patch
mm/page_alloc.c: In function ‘deferred_init_memmap’:
mm/page_alloc.c:1135:4: error: implicit declaration of function ‘meminit_pfn_in_nid’ [-Werror=implicit-function-declaration]
    if (!meminit_pfn_in_nid(pfn, nid, &nid_init_state)) {
    ^

because randconfig decided to disable CONFIG_NODES_SPAN_OTHER_NODES.

Signed-off-by: Michal Hocko <mhocko@suse.cz>