mm: memory-failure: add stub for page_handle_poison()
Fix a build error when no HWPOISON kconfig symbols are set/enabled
by providing a stub function for 'page_handle_poison()'.

../mm/memory-failure.c: In function `__soft_offline_page':
../mm/memory-failure.c:1827:3: error: implicit declaration of function `page_handle_poison'; did you mean `page_init_poison'? [-Werror=implicit-function-declaration]
   page_handle_poison(page, false, true);

Link: http://lkml.kernel.org/r/5bc95fd0-4c21-59c3-4629-7b6848b6a399@infradead.org
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Oscar Salvador <osalvador@suse.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>