mm, debug: mm-introduce-vm_bug_on_mm-fix.patch
dump_mm wants to dump mm->owner even when CONFIG_MEMCG is not defined
which leads to a compilation error:
mm/debug.c: In function ‘dump_mm’:
mm/debug.c:212:5: error: ‘const struct mm_struct’ has no member named ‘owner’
   mm->owner, mm->exe_file,

Signed-off-by: Michal Hocko <mhocko@suse.cz>