mm-mmu_notifier-use-structure-for-invalidate_range_start-end-calls-checkpatch-fixes
ERROR: code indent should use tabs where possible
#102: FILE: include/linux/mm.h:1506:
+^I^I ^I     struct mmu_notifier_range *range,$

WARNING: please, no space before tabs
#102: FILE: include/linux/mm.h:1506:
+^I^I ^I     struct mmu_notifier_range *range,$

WARNING: function definition argument 'struct mmu_notifier_range *' should also have an identifier name
#117: FILE: include/linux/mmu_notifier.h:223:
+extern int __mmu_notifier_invalidate_range_start(struct mmu_notifier_range *);

ERROR: code indent should use tabs where possible
#922: FILE: mm/memory.c:4122:
+^I^I ^I     struct mmu_notifier_range *range,$

WARNING: please, no space before tabs
#922: FILE: mm/memory.c:4122:
+^I^I ^I     struct mmu_notifier_range *range,$

WARNING: line over 80 characters
#1033: FILE: mm/mmu_notifier.c:183:
+						!range->blockable ? "non-" : "");

WARNING: line over 80 characters
#1170: FILE: mm/oom_kill.c:539:
+			if (mmu_notifier_invalidate_range_start_nonblock(&range)) {

WARNING: line over 80 characters
#1178: FILE: mm/oom_kill.c:544:
+			unmap_page_range(&tlb, vma, range.start, range.end, NULL);

total: 2 errors, 6 warnings, 1133 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-mmu_notifier-use-structure-for-invalidate_range_start-end-calls.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Jerome Glisse <jglisse@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>