mm-page_alloc-use-kern_cont-where-appropriate-checkpatch-fixes
WARNING: Prefer [subsystem eg: netdev]_cont([subsystem]dev, ... then dev_cont(dev, ... then pr_cont(...  to printk(KERN_CONT ...
#27: FILE: mm/page_alloc.c:4227:
+	printk(KERN_CONT "(%s) ", tmp);

WARNING: Prefer [subsystem eg: netdev]_cont([subsystem]dev, ... then dev_cont(dev, ... then pr_cont(...  to printk(KERN_CONT ...
#36: FILE: mm/page_alloc.c:4338:
+		printk(KERN_CONT

ERROR: code indent should use tabs where possible
#37: FILE: mm/page_alloc.c:4339:
+^I^I        "%s"$

WARNING: Prefer [subsystem eg: netdev]_cont([subsystem]dev, ... then dev_cont(dev, ... then pr_cont(...  to printk(KERN_CONT ...
#47: FILE: mm/page_alloc.c:4386:
+			printk(KERN_CONT " %ld", zone->lowmem_reserve[i]);

WARNING: Prefer [subsystem eg: netdev]_cont([subsystem]dev, ... then dev_cont(dev, ... then pr_cont(...  to printk(KERN_CONT ...
#48: FILE: mm/page_alloc.c:4387:
+		printk(KERN_CONT "\n");

WARNING: Prefer [subsystem eg: netdev]_cont([subsystem]dev, ... then dev_cont(dev, ... then pr_cont(...  to printk(KERN_CONT ...
#57: FILE: mm/page_alloc.c:4398:
+		printk(KERN_CONT "%s: ", zone->name);

WARNING: Prefer [subsystem eg: netdev]_cont([subsystem]dev, ... then dev_cont(dev, ... then pr_cont(...  to printk(KERN_CONT ...
#66: FILE: mm/page_alloc.c:4416:
+			printk(KERN_CONT "%lu*%lukB ",

WARNING: Prefer [subsystem eg: netdev]_cont([subsystem]dev, ... then dev_cont(dev, ... then pr_cont(...  to printk(KERN_CONT ...
#72: FILE: mm/page_alloc.c:4421:
+		printk(KERN_CONT "= %lukB\n", K(total));

total: 1 errors, 7 warnings, 49 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-page_alloc-use-kern_cont-where-appropriate.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Joe Perches <joe@perches.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>